//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class access_requirement
    {
        public int mapId { get; set; }
        public byte difficulty { get; set; }
        public byte level_min { get; set; }
        public byte level_max { get; set; }
        public int item { get; set; }
        public int item2 { get; set; }
        public int quest_done_A { get; set; }
        public int quest_done_H { get; set; }
        public int completed_achievement { get; set; }
        public string quest_failed_text { get; set; }
        public string comment { get; set; }
    }
}
