//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account()
        {
            this.rbac_account_permissions = new HashSet<rbac_account_permissions>();
        }
    
        public long id { get; set; }
        public string username { get; set; }
        public string sha_pass_hash { get; set; }
        public string sessionkey { get; set; }
        public string v { get; set; }
        public string s { get; set; }
        public string token_key { get; set; }
        public string email { get; set; }
        public string reg_mail { get; set; }
        public System.DateTime joindate { get; set; }
        public string last_ip { get; set; }
        public string last_attempt_ip { get; set; }
        public long failed_logins { get; set; }
        public byte locked { get; set; }
        public string lock_country { get; set; }
        public System.DateTime last_login { get; set; }
        public byte online { get; set; }
        public byte expansion { get; set; }
        public long mutetime { get; set; }
        public string mutereason { get; set; }
        public string muteby { get; set; }
        public byte locale { get; set; }
        public string os { get; set; }
        public long recruiter { get; set; }
        public Nullable<long> battlenet_account { get; set; }
        public Nullable<byte> battlenet_index { get; set; }
    
        public virtual ICollection<rbac_account_permissions> rbac_account_permissions { get; set; }
        public virtual battlenet_accounts battlenet_accounts { get; set; }
    }
}
