//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_last_played_character
    {
        public long accountId { get; set; }
        public byte region { get; set; }
        public byte battlegroup { get; set; }
        public Nullable<long> realmId { get; set; }
        public string characterName { get; set; }
        public Nullable<decimal> characterGUID { get; set; }
        public Nullable<long> lastPlayedTime { get; set; }
    }
}
