//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class achievement
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public long Flags { get; set; }
        public string Reward { get; set; }
        public short MapID { get; set; }
        public int Supercedes { get; set; }
        public int Category { get; set; }
        public int UIOrder { get; set; }
        public int SharesCriteria { get; set; }
        public int CriteriaTree { get; set; }
        public sbyte Faction { get; set; }
        public byte Points { get; set; }
        public byte MinimumCriteria { get; set; }
        public long ID { get; set; }
        public long IconFileDataID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
