//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class archiveEntities : DbContext
    {
        public archiveEntities()
            : base("name=archiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account_data> account_data { get; set; }
        public DbSet<account_instance_times> account_instance_times { get; set; }
        public DbSet<account_tutorial> account_tutorial { get; set; }
        public DbSet<arena_team> arena_team { get; set; }
        public DbSet<arena_team_member> arena_team_member { get; set; }
        public DbSet<auctionhouse> auctionhouses { get; set; }
        public DbSet<blackmarket_auctions> blackmarket_auctions { get; set; }
        public DbSet<bugreport> bugreports { get; set; }
        public DbSet<calendar_events> calendar_events { get; set; }
        public DbSet<calendar_invites> calendar_invites { get; set; }
        public DbSet<channel> channels { get; set; }
        public DbSet<character_account_data> character_account_data { get; set; }
        public DbSet<character_achievement> character_achievement { get; set; }
        public DbSet<character_achievement_progress> character_achievement_progress { get; set; }
        public DbSet<character_action> character_action { get; set; }
        public DbSet<character_arena_stats> character_arena_stats { get; set; }
        public DbSet<character_aura> character_aura { get; set; }
        public DbSet<character_aura_effect> character_aura_effect { get; set; }
        public DbSet<character_banned> character_banned { get; set; }
        public DbSet<character_battleground_data> character_battleground_data { get; set; }
        public DbSet<character_battleground_random> character_battleground_random { get; set; }
        public DbSet<character_cuf_profiles> character_cuf_profiles { get; set; }
        public DbSet<character_currency> character_currency { get; set; }
        public DbSet<character_declinedname> character_declinedname { get; set; }
        public DbSet<character_equipmentsets> character_equipmentsets { get; set; }
        public DbSet<character_fishingsteps> character_fishingsteps { get; set; }
        public DbSet<character_garrison> character_garrison { get; set; }
        public DbSet<character_garrison_blueprints> character_garrison_blueprints { get; set; }
        public DbSet<character_garrison_buildings> character_garrison_buildings { get; set; }
        public DbSet<character_garrison_follower_abilities> character_garrison_follower_abilities { get; set; }
        public DbSet<character_garrison_followers> character_garrison_followers { get; set; }
        public DbSet<character_gifts> character_gifts { get; set; }
        public DbSet<character_glyphs> character_glyphs { get; set; }
        public DbSet<character_homebind> character_homebind { get; set; }
        public DbSet<character_instance> character_instance { get; set; }
        public DbSet<character_inventory> character_inventory { get; set; }
        public DbSet<character_pet> character_pet { get; set; }
        public DbSet<character_pet_declinedname> character_pet_declinedname { get; set; }
        public DbSet<character_queststatus> character_queststatus { get; set; }
        public DbSet<character_queststatus_daily> character_queststatus_daily { get; set; }
        public DbSet<character_queststatus_monthly> character_queststatus_monthly { get; set; }
        public DbSet<character_queststatus_objectives> character_queststatus_objectives { get; set; }
        public DbSet<character_queststatus_objectives_criteria> character_queststatus_objectives_criteria { get; set; }
        public DbSet<character_queststatus_objectives_criteria_progress> character_queststatus_objectives_criteria_progress { get; set; }
        public DbSet<character_queststatus_rewarded> character_queststatus_rewarded { get; set; }
        public DbSet<character_queststatus_seasonal> character_queststatus_seasonal { get; set; }
        public DbSet<character_queststatus_weekly> character_queststatus_weekly { get; set; }
        public DbSet<character_reputation> character_reputation { get; set; }
        public DbSet<character_skills> character_skills { get; set; }
        public DbSet<character_social> character_social { get; set; }
        public DbSet<character_spell> character_spell { get; set; }
        public DbSet<character_spell_cooldown> character_spell_cooldown { get; set; }
        public DbSet<character_stats> character_stats { get; set; }
        public DbSet<character_talent> character_talent { get; set; }
        public DbSet<character_transmog_outfits> character_transmog_outfits { get; set; }
        public DbSet<character_void_storage> character_void_storage { get; set; }
        public DbSet<character> characters { get; set; }
        public DbSet<corpse> corpses { get; set; }
        public DbSet<corpse_phases> corpse_phases { get; set; }
        public DbSet<creature_respawn> creature_respawn { get; set; }
        public DbSet<game_event_condition_save> game_event_condition_save { get; set; }
        public DbSet<game_event_save> game_event_save { get; set; }
        public DbSet<gameobject_respawn> gameobject_respawn { get; set; }
        public DbSet<gm_bug> gm_bug { get; set; }
        public DbSet<gm_complaint> gm_complaint { get; set; }
        public DbSet<gm_complaint_chatlog> gm_complaint_chatlog { get; set; }
        public DbSet<gm_suggestion> gm_suggestion { get; set; }
        public DbSet<group_instance> group_instance { get; set; }
        public DbSet<group_member> group_member { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<guild> guilds { get; set; }
        public DbSet<guild_achievement> guild_achievement { get; set; }
        public DbSet<guild_achievement_progress> guild_achievement_progress { get; set; }
        public DbSet<guild_bank_eventlog> guild_bank_eventlog { get; set; }
        public DbSet<guild_bank_item> guild_bank_item { get; set; }
        public DbSet<guild_bank_right> guild_bank_right { get; set; }
        public DbSet<guild_bank_tab> guild_bank_tab { get; set; }
        public DbSet<guild_eventlog> guild_eventlog { get; set; }
        public DbSet<guild_finder_applicant> guild_finder_applicant { get; set; }
        public DbSet<guild_finder_guild_settings> guild_finder_guild_settings { get; set; }
        public DbSet<guild_member_withdraw> guild_member_withdraw { get; set; }
        public DbSet<guild_newslog> guild_newslog { get; set; }
        public DbSet<guild_rank> guild_rank { get; set; }
        public DbSet<instance> instances { get; set; }
        public DbSet<instance_reset> instance_reset { get; set; }
        public DbSet<instance_scenario_progress> instance_scenario_progress { get; set; }
        public DbSet<item_instance> item_instance { get; set; }
        public DbSet<item_instance_artifact> item_instance_artifact { get; set; }
        public DbSet<item_instance_artifact_powers> item_instance_artifact_powers { get; set; }
        public DbSet<item_instance_gems> item_instance_gems { get; set; }
        public DbSet<item_instance_modifiers> item_instance_modifiers { get; set; }
        public DbSet<item_instance_transmog> item_instance_transmog { get; set; }
        public DbSet<item_loot_items> item_loot_items { get; set; }
        public DbSet<item_loot_money> item_loot_money { get; set; }
        public DbSet<item_refund_instance> item_refund_instance { get; set; }
        public DbSet<item_soulbound_trade_data> item_soulbound_trade_data { get; set; }
        public DbSet<lfg_data> lfg_data { get; set; }
        public DbSet<mail> mails { get; set; }
        public DbSet<mail_items> mail_items { get; set; }
        public DbSet<pet_aura> pet_aura { get; set; }
        public DbSet<pet_aura_effect> pet_aura_effect { get; set; }
        public DbSet<pet_spell> pet_spell { get; set; }
        public DbSet<pet_spell_cooldown> pet_spell_cooldown { get; set; }
        public DbSet<petition> petitions { get; set; }
        public DbSet<petition_sign> petition_sign { get; set; }
        public DbSet<pool_quest_save> pool_quest_save { get; set; }
        public DbSet<pvpstats_battlegrounds> pvpstats_battlegrounds { get; set; }
        public DbSet<pvpstats_players> pvpstats_players { get; set; }
        public DbSet<quest_tracker> quest_tracker { get; set; }
        public DbSet<reserved_name> reserved_name { get; set; }
        public DbSet<update> updates { get; set; }
        public DbSet<updates_include> updates_include { get; set; }
        public DbSet<warden_action> warden_action { get; set; }
        public DbSet<worldstate> worldstates { get; set; }
        public DbSet<character_spell_charges> character_spell_charges { get; set; }
        public DbSet<guild_member> guild_member { get; set; }
        public DbSet<pet_spell_charges> pet_spell_charges { get; set; }
    }
}
