//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class areatrigger_template_polygon_vertices
    {
        public long AreaTriggerId { get; set; }
        public long Idx { get; set; }
        public float VerticeX { get; set; }
        public float VerticeY { get; set; }
        public Nullable<float> VerticeTargetX { get; set; }
        public Nullable<float> VerticeTargetY { get; set; }
        public long VerifiedBuild { get; set; }
    }
}
