//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class areatrigger_template_actions
    {
        public long AreaTriggerId { get; set; }
        public long ActionType { get; set; }
        public long ActionParam { get; set; }
        public long TargetType { get; set; }
    }
}
