//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class areatrigger_template
    {
        public long Id { get; set; }
        public byte Type { get; set; }
        public long Flags { get; set; }
        public float Data0 { get; set; }
        public float Data1 { get; set; }
        public float Data2 { get; set; }
        public float Data3 { get; set; }
        public float Data4 { get; set; }
        public float Data5 { get; set; }
        public string ScriptName { get; set; }
        public long VerifiedBuild { get; set; }
    }
}
