//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class area_table
    {
        public long ID { get; set; }
        public long Flags1 { get; set; }
        public long Flags2 { get; set; }
        public string ZoneName { get; set; }
        public float AmbientMultiplier { get; set; }
        public string AreaName { get; set; }
        public int MapID { get; set; }
        public int ParentAreaID { get; set; }
        public short AreaBit { get; set; }
        public int AmbienceID { get; set; }
        public int ZoneMusic { get; set; }
        public int IntroSound { get; set; }
        public int LiquidTypeID1 { get; set; }
        public int LiquidTypeID2 { get; set; }
        public int LiquidTypeID3 { get; set; }
        public int LiquidTypeID4 { get; set; }
        public int UWZoneMusic { get; set; }
        public int UWAmbience { get; set; }
        public int PvPCombatWorldStateID { get; set; }
        public byte SoundProviderPref { get; set; }
        public byte SoundProviderPrefUnderwater { get; set; }
        public byte ExplorationLevel { get; set; }
        public byte FactionGroupMask { get; set; }
        public byte MountFlags { get; set; }
        public byte WildBattlePetLevelMin { get; set; }
        public byte WildBattlePetLevelMax { get; set; }
        public byte WindSettingsID { get; set; }
        public long UWIntroSound { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
