//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class arena_team
    {
        public long arenaTeamId { get; set; }
        public string name { get; set; }
        public decimal captainGuid { get; set; }
        public byte type { get; set; }
        public int rating { get; set; }
        public int seasonGames { get; set; }
        public int seasonWins { get; set; }
        public int weekGames { get; set; }
        public int weekWins { get; set; }
        public long rank { get; set; }
        public long backgroundColor { get; set; }
        public byte emblemStyle { get; set; }
        public long emblemColor { get; set; }
        public byte borderStyle { get; set; }
        public long borderColor { get; set; }
    }
}
