//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class arena_team_member
    {
        public long arenaTeamId { get; set; }
        public decimal guid { get; set; }
        public int weekGames { get; set; }
        public int weekWins { get; set; }
        public int seasonGames { get; set; }
        public int seasonWins { get; set; }
        public int personalRating { get; set; }
    }
}
