//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class armor_location
    {
        public long ID { get; set; }
        public float Modifier1 { get; set; }
        public float Modifier2 { get; set; }
        public float Modifier3 { get; set; }
        public float Modifier4 { get; set; }
        public float Modifier5 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
