//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class artifact_appearance_set
    {
        public string Name { get; set; }
        public string Name2 { get; set; }
        public int UiCameraID { get; set; }
        public int AltHandUICameraID { get; set; }
        public byte ArtifactID { get; set; }
        public byte DisplayIndex { get; set; }
        public byte AttachmentPoint { get; set; }
        public byte Flags { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
