//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class artifact
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long BarConnectedColor { get; set; }
        public long BarDisconnectedColor { get; set; }
        public long TitleColor { get; set; }
        public int ClassUiTextureKitID { get; set; }
        public int SpecID { get; set; }
        public byte ArtifactCategoryID { get; set; }
        public byte Flags { get; set; }
        public long UiModelSceneID { get; set; }
        public long SpellVisualKitID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
