//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class artifact_appearance
    {
        public string Name { get; set; }
        public long SwatchColor { get; set; }
        public float ModelDesaturation { get; set; }
        public float ModelAlpha { get; set; }
        public long ShapeshiftDisplayID { get; set; }
        public int ArtifactAppearanceSetID { get; set; }
        public int Unknown { get; set; }
        public byte DisplayIndex { get; set; }
        public byte AppearanceModID { get; set; }
        public byte Flags { get; set; }
        public byte ModifiesShapeshiftFormDisplay { get; set; }
        public long ID { get; set; }
        public long PlayerConditionID { get; set; }
        public long ItemAppearanceID { get; set; }
        public long AltItemAppearanceID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
