//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class artifact_quest_xp
    {
        public long ID { get; set; }
        public long Exp1 { get; set; }
        public long Exp2 { get; set; }
        public long Exp3 { get; set; }
        public long Exp4 { get; set; }
        public long Exp5 { get; set; }
        public long Exp6 { get; set; }
        public long Exp7 { get; set; }
        public long Exp8 { get; set; }
        public long Exp9 { get; set; }
        public long Exp10 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
