//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class artifact_power
    {
        public float PosX { get; set; }
        public float PosY { get; set; }
        public byte ArtifactID { get; set; }
        public byte Flags { get; set; }
        public byte MaxRank { get; set; }
        public byte ArtifactTier { get; set; }
        public long ID { get; set; }
        public int RelicType { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
