//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class artifact_power_rank
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public float Value { get; set; }
        public int ArtifactPowerID { get; set; }
        public int Unknown { get; set; }
        public byte Rank { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
