//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class auctionhouse
    {
        public long id { get; set; }
        public decimal auctioneerguid { get; set; }
        public decimal itemguid { get; set; }
        public decimal itemowner { get; set; }
        public decimal buyoutprice { get; set; }
        public long time { get; set; }
        public decimal buyguid { get; set; }
        public decimal lastbid { get; set; }
        public decimal startbid { get; set; }
        public decimal deposit { get; set; }
    }
}
