//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class battle_pets
    {
        public long guid { get; set; }
        public int battlenetAccountId { get; set; }
        public int species { get; set; }
        public short breed { get; set; }
        public short level { get; set; }
        public short exp { get; set; }
        public int health { get; set; }
        public sbyte quality { get; set; }
        public short flags { get; set; }
        public string name { get; set; }
    }
}
