//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class battlenet_item_favorite_appearances
    {
        public long battlenetAccountId { get; set; }
        public long itemModifiedAppearanceId { get; set; }
    
        public virtual battlenet_accounts battlenet_accounts { get; set; }
    }
}
