//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class battlemaster_list
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long IconFileDataID { get; set; }
        public string GameType { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public short MapID1 { get; set; }
        public short MapID2 { get; set; }
        public short MapID3 { get; set; }
        public short MapID4 { get; set; }
        public short MapID5 { get; set; }
        public short MapID6 { get; set; }
        public short MapID7 { get; set; }
        public short MapID8 { get; set; }
        public short MapID9 { get; set; }
        public short MapID10 { get; set; }
        public short MapID11 { get; set; }
        public short MapID12 { get; set; }
        public short MapID13 { get; set; }
        public short MapID14 { get; set; }
        public short MapID15 { get; set; }
        public short MapID16 { get; set; }
        public int HolidayWorldState { get; set; }
        public int PlayerConditionID { get; set; }
        public byte InstanceType { get; set; }
        public byte GroupsAllowed { get; set; }
        public byte MaxGroupSize { get; set; }
        public byte MinLevel { get; set; }
        public byte MaxLevel { get; set; }
        public byte RatedPlayers { get; set; }
        public byte MinPlayers { get; set; }
        public byte MaxPlayers { get; set; }
        public byte Flags { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
