//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class battle_pet_slots
    {
        public sbyte id { get; set; }
        public int battlenetAccountId { get; set; }
        public long battlePetGuid { get; set; }
        public sbyte locked { get; set; }
    }
}
