//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class battle_pet_species_state
    {
        public long ID { get; set; }
        public int Value { get; set; }
        public int SpeciesID { get; set; }
        public byte State { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
