//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class battle_pet_species
    {
        public long CreatureID { get; set; }
        public long IconFileID { get; set; }
        public long SummonSpellID { get; set; }
        public string SourceText { get; set; }
        public string Description { get; set; }
        public int Flags { get; set; }
        public byte PetType { get; set; }
        public sbyte Source { get; set; }
        public long ID { get; set; }
        public long CardModelSceneID { get; set; }
        public long LoadoutModelSceneID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
