//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class broadcast_text
    {
        public long ID { get; set; }
        public string MaleText { get; set; }
        public string FemaleText { get; set; }
        public int EmoteID1 { get; set; }
        public int EmoteID2 { get; set; }
        public int EmoteID3 { get; set; }
        public int EmoteDelay1 { get; set; }
        public int EmoteDelay2 { get; set; }
        public int EmoteDelay3 { get; set; }
        public int UnkEmoteID { get; set; }
        public byte Language { get; set; }
        public byte Type { get; set; }
        public long SoundID1 { get; set; }
        public long SoundID2 { get; set; }
        public long PlayerConditionID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
