//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendar_invites
    {
        public decimal InviteID { get; set; }
        public decimal EventID { get; set; }
        public decimal Invitee { get; set; }
        public decimal Sender { get; set; }
        public bool Status { get; set; }
        public long ResponseTime { get; set; }
        public bool ModerationRank { get; set; }
        public string Note { get; set; }
    }
}
