//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendar_events
    {
        public decimal EventID { get; set; }
        public decimal Owner { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool EventType { get; set; }
        public int TextureID { get; set; }
        public long Date { get; set; }
        public long Flags { get; set; }
        public long LockDate { get; set; }
    }
}
