//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class channel
    {
        public string name { get; set; }
        public long team { get; set; }
        public byte announce { get; set; }
        public byte ownership { get; set; }
        public string password { get; set; }
        public string bannedList { get; set; }
        public long lastUsed { get; set; }
    }
}
