//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_void_storage
    {
        public decimal itemId { get; set; }
        public decimal playerGuid { get; set; }
        public int itemEntry { get; set; }
        public byte slot { get; set; }
        public decimal creatorGuid { get; set; }
        public byte randomPropertyType { get; set; }
        public long randomProperty { get; set; }
        public long suffixFactor { get; set; }
        public long upgradeId { get; set; }
        public Nullable<long> fixedScalingLevel { get; set; }
        public Nullable<long> artifactKnowledgeLevel { get; set; }
        public byte context { get; set; }
        public string bonusListIDs { get; set; }
    }
}
