//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_battleground_data
    {
        public decimal guid { get; set; }
        public long instanceId { get; set; }
        public int team { get; set; }
        public float joinX { get; set; }
        public float joinY { get; set; }
        public float joinZ { get; set; }
        public float joinO { get; set; }
        public int joinMapId { get; set; }
        public long taxiStart { get; set; }
        public long taxiEnd { get; set; }
        public int mountSpell { get; set; }
    }
}
