//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character
    {
        public character()
        {
            this.character_garrison_followers = new HashSet<character_garrison_followers>();
        }
    
        public decimal guid { get; set; }
        public long account { get; set; }
        public string name { get; set; }
        public byte slot { get; set; }
        public byte race { get; set; }
        public byte @class { get; set; }
        public byte gender { get; set; }
        public byte level { get; set; }
        public long xp { get; set; }
        public decimal money { get; set; }
        public byte skin { get; set; }
        public byte face { get; set; }
        public byte hairStyle { get; set; }
        public byte hairColor { get; set; }
        public byte facialStyle { get; set; }
        public byte customDisplay1 { get; set; }
        public byte customDisplay2 { get; set; }
        public byte customDisplay3 { get; set; }
        public byte bankSlots { get; set; }
        public byte restState { get; set; }
        public long playerFlags { get; set; }
        public long playerFlagsEx { get; set; }
        public float position_x { get; set; }
        public float position_y { get; set; }
        public float position_z { get; set; }
        public int map { get; set; }
        public long instance_id { get; set; }
        public byte dungeonDifficulty { get; set; }
        public byte raidDifficulty { get; set; }
        public byte legacyRaidDifficulty { get; set; }
        public float orientation { get; set; }
        public string taximask { get; set; }
        public byte online { get; set; }
        public byte cinematic { get; set; }
        public long totaltime { get; set; }
        public long leveltime { get; set; }
        public long logout_time { get; set; }
        public byte is_logout_resting { get; set; }
        public float rest_bonus { get; set; }
        public long resettalents_cost { get; set; }
        public long resettalents_time { get; set; }
        public long primarySpecialization { get; set; }
        public float trans_x { get; set; }
        public float trans_y { get; set; }
        public float trans_z { get; set; }
        public float trans_o { get; set; }
        public decimal transguid { get; set; }
        public int extra_flags { get; set; }
        public byte stable_slots { get; set; }
        public int at_login { get; set; }
        public int zone { get; set; }
        public long death_expire_time { get; set; }
        public string taxi_path { get; set; }
        public long totalKills { get; set; }
        public int todayKills { get; set; }
        public int yesterdayKills { get; set; }
        public long chosenTitle { get; set; }
        public long watchedFaction { get; set; }
        public byte drunk { get; set; }
        public long health { get; set; }
        public long power1 { get; set; }
        public long power2 { get; set; }
        public long power3 { get; set; }
        public long power4 { get; set; }
        public long power5 { get; set; }
        public long power6 { get; set; }
        public int latency { get; set; }
        public byte activeTalentGroup { get; set; }
        public long lootSpecId { get; set; }
        public string exploredZones { get; set; }
        public string equipmentCache { get; set; }
        public string knownTitles { get; set; }
        public byte actionBars { get; set; }
        public byte grantableLevels { get; set; }
        public Nullable<long> deleteInfos_Account { get; set; }
        public string deleteInfos_Name { get; set; }
        public Nullable<long> deleteDate { get; set; }
        public long honor { get; set; }
        public long honorLevel { get; set; }
        public long prestigeLevel { get; set; }
        public byte honorRestState { get; set; }
        public float honorRestBonus { get; set; }
    
        public virtual ICollection<character_garrison_followers> character_garrison_followers { get; set; }
    }
}
