//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_base
    {
        public int entry { get; set; }
        public int account_id { get; set; }
        public int character_guid { get; set; }
        public string character_name { get; set; }
        public int character_race { get; set; }
        public int character_class { get; set; }
        public int character_skin { get; set; }
        public int character_face { get; set; }
        public int character_hair_style { get; set; }
        public int character_hair_color { get; set; }
        public int character_facial_hair { get; set; }
        public int character_outfit { get; set; }
    }
}
