//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_pet
    {
        public long id { get; set; }
        public long entry { get; set; }
        public decimal owner { get; set; }
        public Nullable<long> modelid { get; set; }
        public int CreatedBySpell { get; set; }
        public byte PetType { get; set; }
        public int level { get; set; }
        public long exp { get; set; }
        public byte Reactstate { get; set; }
        public string name { get; set; }
        public byte renamed { get; set; }
        public byte slot { get; set; }
        public long curhealth { get; set; }
        public long curmana { get; set; }
        public long savetime { get; set; }
        public string abdata { get; set; }
        public int specialization { get; set; }
    }
}
