//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_garrison_followers
    {
        public character_garrison_followers()
        {
            this.character_garrison_follower_abilities = new HashSet<character_garrison_follower_abilities>();
        }
    
        public decimal dbId { get; set; }
        public decimal guid { get; set; }
        public long followerId { get; set; }
        public long quality { get; set; }
        public long level { get; set; }
        public long itemLevelWeapon { get; set; }
        public long itemLevelArmor { get; set; }
        public long xp { get; set; }
        public long currentBuilding { get; set; }
        public long currentMission { get; set; }
        public long status { get; set; }
    
        public virtual ICollection<character_garrison_follower_abilities> character_garrison_follower_abilities { get; set; }
        public virtual character character { get; set; }
    }
}
