//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_aura
    {
        public decimal guid { get; set; }
        public System.Guid casterGuid { get; set; }
        public System.Guid itemGuid { get; set; }
        public long spell { get; set; }
        public long effectMask { get; set; }
        public long recalculateMask { get; set; }
        public byte stackCount { get; set; }
        public int maxDuration { get; set; }
        public int remainTime { get; set; }
        public byte remainCharges { get; set; }
        public int castItemLevel { get; set; }
    }
}
