//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_equipmentsets
    {
        public long guid { get; set; }
        public long setguid { get; set; }
        public byte setindex { get; set; }
        public string name { get; set; }
        public string iconname { get; set; }
        public long ignore_mask { get; set; }
        public int AssignedSpecIndex { get; set; }
        public decimal item0 { get; set; }
        public decimal item1 { get; set; }
        public decimal item2 { get; set; }
        public decimal item3 { get; set; }
        public decimal item4 { get; set; }
        public decimal item5 { get; set; }
        public decimal item6 { get; set; }
        public decimal item7 { get; set; }
        public decimal item8 { get; set; }
        public decimal item9 { get; set; }
        public decimal item10 { get; set; }
        public decimal item11 { get; set; }
        public decimal item12 { get; set; }
        public decimal item13 { get; set; }
        public decimal item14 { get; set; }
        public decimal item15 { get; set; }
        public decimal item16 { get; set; }
        public decimal item17 { get; set; }
        public decimal item18 { get; set; }
    }
}
