//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_inventory
    {
        public decimal guid { get; set; }
        public decimal bag { get; set; }
        public byte slot { get; set; }
        public decimal item { get; set; }
    }
}
