//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_pet_declinedname
    {
        public long id { get; set; }
        public long owner { get; set; }
        public string genitive { get; set; }
        public string dative { get; set; }
        public string accusative { get; set; }
        public string instrumental { get; set; }
        public string prepositional { get; set; }
    }
}
