//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_transmog_outfits
    {
        public long guid { get; set; }
        public long setguid { get; set; }
        public byte setindex { get; set; }
        public string name { get; set; }
        public string iconname { get; set; }
        public int ignore_mask { get; set; }
        public int appearance0 { get; set; }
        public int appearance1 { get; set; }
        public int appearance2 { get; set; }
        public int appearance3 { get; set; }
        public int appearance4 { get; set; }
        public int appearance5 { get; set; }
        public int appearance6 { get; set; }
        public int appearance7 { get; set; }
        public int appearance8 { get; set; }
        public int appearance9 { get; set; }
        public int appearance10 { get; set; }
        public int appearance11 { get; set; }
        public int appearance12 { get; set; }
        public int appearance13 { get; set; }
        public int appearance14 { get; set; }
        public int appearance15 { get; set; }
        public int appearance16 { get; set; }
        public int appearance17 { get; set; }
        public int appearance18 { get; set; }
        public int mainHandEnchant { get; set; }
        public int offHandEnchant { get; set; }
    }
}
