//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_cuf_profiles
    {
        public decimal guid { get; set; }
        public byte id { get; set; }
        public string name { get; set; }
        public int frameHeight { get; set; }
        public int frameWidth { get; set; }
        public byte sortBy { get; set; }
        public byte healthText { get; set; }
        public long boolOptions { get; set; }
        public byte topPoint { get; set; }
        public byte bottomPoint { get; set; }
        public byte leftPoint { get; set; }
        public int topOffset { get; set; }
        public int bottomOffset { get; set; }
        public int leftOffset { get; set; }
    }
}
