//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_currency
    {
        public decimal CharacterGuid { get; set; }
        public int Currency { get; set; }
        public long Quantity { get; set; }
        public long WeeklyQuantity { get; set; }
        public long TrackedQuantity { get; set; }
        public byte Flags { get; set; }
    }
}
