//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class char_sections
    {
        public long ID { get; set; }
        public long TextureFileDataID1 { get; set; }
        public long TextureFileDataID2 { get; set; }
        public long TextureFileDataID3 { get; set; }
        public int Flags { get; set; }
        public byte RaceID { get; set; }
        public byte SexID { get; set; }
        public byte BaseSection { get; set; }
        public byte VariationIndex { get; set; }
        public byte ColorIndex { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
