//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class char_start_outfit
    {
        public long ID { get; set; }
        public int ItemID1 { get; set; }
        public int ItemID2 { get; set; }
        public int ItemID3 { get; set; }
        public int ItemID4 { get; set; }
        public int ItemID5 { get; set; }
        public int ItemID6 { get; set; }
        public int ItemID7 { get; set; }
        public int ItemID8 { get; set; }
        public int ItemID9 { get; set; }
        public int ItemID10 { get; set; }
        public int ItemID11 { get; set; }
        public int ItemID12 { get; set; }
        public int ItemID13 { get; set; }
        public int ItemID14 { get; set; }
        public int ItemID15 { get; set; }
        public int ItemID16 { get; set; }
        public int ItemID17 { get; set; }
        public int ItemID18 { get; set; }
        public int ItemID19 { get; set; }
        public int ItemID20 { get; set; }
        public int ItemID21 { get; set; }
        public int ItemID22 { get; set; }
        public int ItemID23 { get; set; }
        public int ItemID24 { get; set; }
        public long PetDisplayID { get; set; }
        public byte RaceID { get; set; }
        public byte ClassID { get; set; }
        public byte GenderID { get; set; }
        public byte OutfitID { get; set; }
        public byte PetFamilyID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
