//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class chr_races
    {
        public long ID { get; set; }
        public long Flags { get; set; }
        public string ClientPrefix { get; set; }
        public string ClientFileString { get; set; }
        public string Name { get; set; }
        public string NameFemale { get; set; }
        public string NameMale { get; set; }
        public string FacialHairCustomization1 { get; set; }
        public string FacialHairCustomization2 { get; set; }
        public string HairCustomization { get; set; }
        public long CreateScreenFileDataID { get; set; }
        public long SelectScreenFileDataID { get; set; }
        public float MaleCustomizeOffset1 { get; set; }
        public float MaleCustomizeOffset2 { get; set; }
        public float MaleCustomizeOffset3 { get; set; }
        public float FemaleCustomizeOffset1 { get; set; }
        public float FemaleCustomizeOffset2 { get; set; }
        public float FemaleCustomizeOffset3 { get; set; }
        public long LowResScreenFileDataID { get; set; }
        public int FactionID { get; set; }
        public int MaleDisplayID { get; set; }
        public int FemaleDisplayID { get; set; }
        public int ResSicknessSpellID { get; set; }
        public int SplashSoundID { get; set; }
        public int CinematicSequenceID { get; set; }
        public byte BaseLanguage { get; set; }
        public byte CreatureType { get; set; }
        public byte TeamID { get; set; }
        public byte RaceRelated { get; set; }
        public byte UnalteredVisualRaceID { get; set; }
        public byte CharComponentTextureLayoutID { get; set; }
        public byte DefaultClassID { get; set; }
        public byte NeutralRaceID { get; set; }
        public byte ItemAppearanceFrameRaceID { get; set; }
        public byte CharComponentTexLayoutHiResID { get; set; }
        public long HighResMaleDisplayID { get; set; }
        public long HighResFemaleDisplayID { get; set; }
        public long Unk1 { get; set; }
        public long Unk2 { get; set; }
        public long Unk3 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
