//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class chr_classes
    {
        public string PetNameToken { get; set; }
        public string Name { get; set; }
        public string NameFemale { get; set; }
        public string NameMale { get; set; }
        public string Filename { get; set; }
        public long CreateScreenFileDataID { get; set; }
        public long SelectScreenFileDataID { get; set; }
        public long IconFileDataID { get; set; }
        public long LowResScreenFileDataID { get; set; }
        public int Flags { get; set; }
        public int CinematicSequenceID { get; set; }
        public int DefaultSpec { get; set; }
        public byte PowerType { get; set; }
        public byte SpellClassSet { get; set; }
        public byte AttackPowerPerStrength { get; set; }
        public byte AttackPowerPerAgility { get; set; }
        public byte RangedAttackPowerPerAgility { get; set; }
        public byte Unk1 { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
