//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class chr_classes_x_power_types
    {
        public long ID { get; set; }
        public byte ClassID { get; set; }
        public byte PowerType { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
