//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class chr_specialization
    {
        public long MasterySpellID1 { get; set; }
        public long MasterySpellID2 { get; set; }
        public string Name { get; set; }
        public string Name2 { get; set; }
        public string Description { get; set; }
        public byte ClassID { get; set; }
        public byte OrderIndex { get; set; }
        public byte PetTalentType { get; set; }
        public byte Role { get; set; }
        public byte PrimaryStatOrder { get; set; }
        public long ID { get; set; }
        public long IconFileDataID { get; set; }
        public long Flags { get; set; }
        public long AnimReplacementSetID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
