//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cinematic_sequences
    {
        public long ID { get; set; }
        public long SoundID { get; set; }
        public int Camera1 { get; set; }
        public int Camera2 { get; set; }
        public int Camera3 { get; set; }
        public int Camera4 { get; set; }
        public int Camera5 { get; set; }
        public int Camera6 { get; set; }
        public int Camera7 { get; set; }
        public int Camera8 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
