//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversation_actors
    {
        public long ConversationId { get; set; }
        public long ConversationActorId { get; set; }
        public decimal ConversationActorGuid { get; set; }
        public int Idx { get; set; }
        public long VerifiedBuild { get; set; }
    }
}
