//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversation_template
    {
        public long Id { get; set; }
        public long FirstLineId { get; set; }
        public long LastLineEndTime { get; set; }
        public string ScriptName { get; set; }
        public long VerifiedBuild { get; set; }
    }
}
