//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversation_line
    {
        public long ID { get; set; }
        public long BroadcastTextID { get; set; }
        public long SpellVisualKitID { get; set; }
        public long Duration { get; set; }
        public int NextLineID { get; set; }
        public int Unk1 { get; set; }
        public byte Yell { get; set; }
        public byte Unk2 { get; set; }
        public byte Unk3 { get; set; }
        public long VerifiedBuild { get; set; }
    }
}
