//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class corpse
    {
        public decimal guid { get; set; }
        public float posX { get; set; }
        public float posY { get; set; }
        public float posZ { get; set; }
        public float orientation { get; set; }
        public int mapId { get; set; }
        public long displayId { get; set; }
        public string itemCache { get; set; }
        public long bytes1 { get; set; }
        public long bytes2 { get; set; }
        public byte flags { get; set; }
        public byte dynFlags { get; set; }
        public long time { get; set; }
        public byte corpseType { get; set; }
        public long instanceId { get; set; }
    }
}
