//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_display_info
    {
        public long ID { get; set; }
        public float CreatureModelScale { get; set; }
        public int ModelID { get; set; }
        public int NPCSoundID { get; set; }
        public byte SizeClass { get; set; }
        public byte Flags { get; set; }
        public sbyte Gender { get; set; }
        public long ExtendedDisplayInfoID { get; set; }
        public long TextureVariation1 { get; set; }
        public long TextureVariation2 { get; set; }
        public long TextureVariation3 { get; set; }
        public long PortraitTextureFileDataID { get; set; }
        public byte CreatureModelAlpha { get; set; }
        public int SoundID { get; set; }
        public float PlayerModelScale { get; set; }
        public long PortraitCreatureDisplayInfoID { get; set; }
        public byte BloodID { get; set; }
        public int ParticleColorID { get; set; }
        public long CreatureGeosetData { get; set; }
        public int ObjectEffectPackageID { get; set; }
        public int AnimReplacementSetID { get; set; }
        public sbyte UnarmedWeaponSubclass { get; set; }
        public long StateSpellVisualKitID { get; set; }
        public float InstanceOtherPlayerPetScale { get; set; }
        public long MountSpellVisualKitID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
