//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature
    {
        public decimal guid { get; set; }
        public int id { get; set; }
        public int map { get; set; }
        public int zoneId { get; set; }
        public int areaId { get; set; }
        public long spawnMask { get; set; }
        public Nullable<int> PhaseId { get; set; }
        public Nullable<int> PhaseGroup { get; set; }
        public int modelid { get; set; }
        public sbyte equipment_id { get; set; }
        public float position_x { get; set; }
        public float position_y { get; set; }
        public float position_z { get; set; }
        public float orientation { get; set; }
        public long spawntimesecs { get; set; }
        public float spawndist { get; set; }
        public int currentwaypoint { get; set; }
        public long curhealth { get; set; }
        public long curmana { get; set; }
        public byte MovementType { get; set; }
        public decimal npcflag { get; set; }
        public long unit_flags { get; set; }
        public long unit_flags2 { get; set; }
        public long unit_flags3 { get; set; }
        public long dynamicflags { get; set; }
        public string ScriptName { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
