//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_text
    {
        public int CreatureID { get; set; }
        public byte GroupID { get; set; }
        public byte ID { get; set; }
        public string Text { get; set; }
        public byte Type { get; set; }
        public sbyte Language { get; set; }
        public int Emote { get; set; }
        public int Duration { get; set; }
        public int Sound { get; set; }
        public int BroadcastTextId { get; set; }
        public byte TextRange { get; set; }
        public string comment { get; set; }
    }
}
