//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_display_info_extra
    {
        public long ID { get; set; }
        public long FileDataID { get; set; }
        public long HDFileDataID { get; set; }
        public byte DisplayRaceID { get; set; }
        public byte DisplaySexID { get; set; }
        public byte DisplayClassID { get; set; }
        public byte SkinID { get; set; }
        public byte FaceID { get; set; }
        public byte HairStyleID { get; set; }
        public byte HairColorID { get; set; }
        public byte FacialHairID { get; set; }
        public byte CustomDisplayOption1 { get; set; }
        public byte CustomDisplayOption2 { get; set; }
        public byte CustomDisplayOption3 { get; set; }
        public byte Flags { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
