//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template_scaling
    {
        public int Entry { get; set; }
        public int LevelScalingMin { get; set; }
        public int LevelScalingMax { get; set; }
        public short LevelScalingDelta { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
