//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_family
    {
        public long ID { get; set; }
        public float MinScale { get; set; }
        public float MaxScale { get; set; }
        public string Name { get; set; }
        public long IconFileDataID { get; set; }
        public int SkillLine1 { get; set; }
        public int SkillLine2 { get; set; }
        public int PetFoodMask { get; set; }
        public byte MinScaleLevel { get; set; }
        public byte MaxScaleLevel { get; set; }
        public byte PetTalentType { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
