//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template_locale
    {
        public int entry { get; set; }
        public string locale { get; set; }
        public string Name { get; set; }
        public string NameAlt { get; set; }
        public string Title { get; set; }
        public string TitleAlt { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
