//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_formations
    {
        public decimal leaderGUID { get; set; }
        public decimal memberGUID { get; set; }
        public long groupAI { get; set; }
        public int point_1 { get; set; }
        public int point_2 { get; set; }
    }
}
