//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_classlevelstats
    {
        public sbyte level { get; set; }
        public sbyte @class { get; set; }
        public int basemana { get; set; }
        public int basearmor { get; set; }
        public short attackpower { get; set; }
        public short rangedattackpower { get; set; }
        public float damage_base { get; set; }
        public float damage_exp1 { get; set; }
        public float damage_exp2 { get; set; }
        public float damage_exp3 { get; set; }
        public float damage_exp4 { get; set; }
        public float damage_exp5 { get; set; }
        public string comment { get; set; }
    }
}
