//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_addon
    {
        public decimal guid { get; set; }
        public long path_id { get; set; }
        public int mount { get; set; }
        public long bytes1 { get; set; }
        public long bytes2 { get; set; }
        public long emote { get; set; }
        public short aiAnimKit { get; set; }
        public short movementAnimKit { get; set; }
        public short meleeAnimKit { get; set; }
        public string auras { get; set; }
    }
}
