//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_difficulty
    {
        public int ID { get; set; }
        public int CreatureID { get; set; }
        public long Flags1 { get; set; }
        public long Flags2 { get; set; }
        public long Flags3 { get; set; }
        public long Flags4 { get; set; }
        public long Flags5 { get; set; }
        public long Flags6 { get; set; }
        public long Flags7 { get; set; }
        public int FactionTemplateID { get; set; }
        public sbyte Expansion { get; set; }
        public sbyte MinLevel { get; set; }
        public sbyte MaxLevel { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
