//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_equip_template
    {
        public int CreatureID { get; set; }
        public byte ID { get; set; }
        public int ItemID1 { get; set; }
        public int AppearanceModID1 { get; set; }
        public int ItemVisual1 { get; set; }
        public int ItemID2 { get; set; }
        public int AppearanceModID2 { get; set; }
        public int ItemVisual2 { get; set; }
        public int ItemID3 { get; set; }
        public int AppearanceModID3 { get; set; }
        public int ItemVisual3 { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
