//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_summon_groups
    {
        public int summonerId { get; set; }
        public byte summonerType { get; set; }
        public byte groupId { get; set; }
        public int entry { get; set; }
        public float position_x { get; set; }
        public float position_y { get; set; }
        public float position_z { get; set; }
        public float orientation { get; set; }
        public byte summonType { get; set; }
        public long summonTime { get; set; }
    }
}
