//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_model_data
    {
        public long ID { get; set; }
        public float ModelScale { get; set; }
        public float FootprintTextureLength { get; set; }
        public float FootprintTextureWidth { get; set; }
        public float FootprintParticleScale { get; set; }
        public float CollisionWidth { get; set; }
        public float CollisionHeight { get; set; }
        public float MountHeight { get; set; }
        public float GeoBoxMin1 { get; set; }
        public float GeoBoxMin2 { get; set; }
        public float GeoBoxMin3 { get; set; }
        public float GeoBoxMax1 { get; set; }
        public float GeoBoxMax2 { get; set; }
        public float GeoBoxMax3 { get; set; }
        public float WorldEffectScale { get; set; }
        public float AttachedEffectScale { get; set; }
        public float MissileCollisionRadius { get; set; }
        public float MissileCollisionPush { get; set; }
        public float MissileCollisionRaise { get; set; }
        public float OverrideLootEffectScale { get; set; }
        public float OverrideNameScale { get; set; }
        public float OverrideSelectionRadius { get; set; }
        public float TamedPetBaseScale { get; set; }
        public float HoverHeight { get; set; }
        public long Flags { get; set; }
        public long FileDataID { get; set; }
        public long SizeClass { get; set; }
        public long BloodID { get; set; }
        public long FootprintTextureID { get; set; }
        public long FoleyMaterialID { get; set; }
        public long FootstepEffectID { get; set; }
        public long DeathThudEffectID { get; set; }
        public long SoundID { get; set; }
        public long CreatureGeosetDataID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
