//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_model_info
    {
        public int DisplayID { get; set; }
        public float BoundingRadius { get; set; }
        public float CombatReach { get; set; }
        public int DisplayID_Other_Gender { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
