//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class criterion
    {
        public long ID { get; set; }
        public long Asset { get; set; }
        public long StartAsset { get; set; }
        public long FailAsset { get; set; }
        public int StartTimer { get; set; }
        public int ModifierTreeId { get; set; }
        public int EligibilityWorldStateID { get; set; }
        public byte Type { get; set; }
        public byte StartEvent { get; set; }
        public byte FailEvent { get; set; }
        public byte Flags { get; set; }
        public byte EligibilityWorldStateValue { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
