//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency_types
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long MaxQty { get; set; }
        public long MaxEarnablePerWeek { get; set; }
        public long Flags { get; set; }
        public string Description { get; set; }
        public byte CategoryID { get; set; }
        public byte SpellCategory { get; set; }
        public byte Quality { get; set; }
        public long InventoryIconFileDataID { get; set; }
        public long SpellWeight { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
