//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class destructible_model_data
    {
        public long ID { get; set; }
        public int StateDamagedDisplayID { get; set; }
        public int StateDestroyedDisplayID { get; set; }
        public int StateRebuildingDisplayID { get; set; }
        public int StateSmokeDisplayID { get; set; }
        public int HealEffectSpeed { get; set; }
        public byte StateDamagedImpactEffectDoodadSet { get; set; }
        public byte StateDamagedAmbientDoodadSet { get; set; }
        public byte StateDamagedNameSet { get; set; }
        public byte StateDestroyedDestructionDoodadSet { get; set; }
        public byte StateDestroyedImpactEffectDoodadSet { get; set; }
        public byte StateDestroyedAmbientDoodadSet { get; set; }
        public byte StateDestroyedNameSet { get; set; }
        public byte StateRebuildingDestructionDoodadSet { get; set; }
        public byte StateRebuildingImpactEffectDoodadSet { get; set; }
        public byte StateRebuildingAmbientDoodadSet { get; set; }
        public byte StateRebuildingNameSet { get; set; }
        public byte StateSmokeInitDoodadSet { get; set; }
        public byte StateSmokeAmbientDoodadSet { get; set; }
        public byte StateSmokeNameSet { get; set; }
        public byte EjectDirection { get; set; }
        public byte DoNotHighlight { get; set; }
        public byte HealEffect { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
