//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class durability_costs
    {
        public long ID { get; set; }
        public int WeaponSubClassCost1 { get; set; }
        public int WeaponSubClassCost2 { get; set; }
        public int WeaponSubClassCost3 { get; set; }
        public int WeaponSubClassCost4 { get; set; }
        public int WeaponSubClassCost5 { get; set; }
        public int WeaponSubClassCost6 { get; set; }
        public int WeaponSubClassCost7 { get; set; }
        public int WeaponSubClassCost8 { get; set; }
        public int WeaponSubClassCost9 { get; set; }
        public int WeaponSubClassCost10 { get; set; }
        public int WeaponSubClassCost11 { get; set; }
        public int WeaponSubClassCost12 { get; set; }
        public int WeaponSubClassCost13 { get; set; }
        public int WeaponSubClassCost14 { get; set; }
        public int WeaponSubClassCost15 { get; set; }
        public int WeaponSubClassCost16 { get; set; }
        public int WeaponSubClassCost17 { get; set; }
        public int WeaponSubClassCost18 { get; set; }
        public int WeaponSubClassCost19 { get; set; }
        public int WeaponSubClassCost20 { get; set; }
        public int WeaponSubClassCost21 { get; set; }
        public int ArmorSubClassCost1 { get; set; }
        public int ArmorSubClassCost2 { get; set; }
        public int ArmorSubClassCost3 { get; set; }
        public int ArmorSubClassCost4 { get; set; }
        public int ArmorSubClassCost5 { get; set; }
        public int ArmorSubClassCost6 { get; set; }
        public int ArmorSubClassCost7 { get; set; }
        public int ArmorSubClassCost8 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
