//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class emote
    {
        public long ID { get; set; }
        public string EmoteSlashCommand { get; set; }
        public long SpellVisualKitID { get; set; }
        public long EmoteFlags { get; set; }
        public int RaceMask { get; set; }
        public int AnimID { get; set; }
        public byte EmoteSpecProc { get; set; }
        public long EmoteSpecProcParam { get; set; }
        public long EmoteSoundID { get; set; }
        public int ClassMask { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
