//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_scripts
    {
        public int id { get; set; }
        public long delay { get; set; }
        public int command { get; set; }
        public int datalong { get; set; }
        public long datalong2 { get; set; }
        public int dataint { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
        public float o { get; set; }
    }
}
