//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class faction
    {
        public long ID { get; set; }
        public long ReputationRaceMask1 { get; set; }
        public long ReputationRaceMask2 { get; set; }
        public long ReputationRaceMask3 { get; set; }
        public long ReputationRaceMask4 { get; set; }
        public int ReputationBase1 { get; set; }
        public int ReputationBase2 { get; set; }
        public int ReputationBase3 { get; set; }
        public int ReputationBase4 { get; set; }
        public float ParentFactionModIn { get; set; }
        public float ParentFactionModOut { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long ReputationMax1 { get; set; }
        public long ReputationMax2 { get; set; }
        public long ReputationMax3 { get; set; }
        public long ReputationMax4 { get; set; }
        public short ReputationIndex { get; set; }
        public int ReputationClassMask1 { get; set; }
        public int ReputationClassMask2 { get; set; }
        public int ReputationClassMask3 { get; set; }
        public int ReputationClassMask4 { get; set; }
        public int ReputationFlags1 { get; set; }
        public int ReputationFlags2 { get; set; }
        public int ReputationFlags3 { get; set; }
        public int ReputationFlags4 { get; set; }
        public int ParentFactionID { get; set; }
        public int ParagonFactionID { get; set; }
        public byte ParentFactionCapIn { get; set; }
        public byte ParentFactionCapOut { get; set; }
        public byte Expansion { get; set; }
        public byte Flags { get; set; }
        public byte FriendshipRepID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
