//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject_display_info
    {
        public long ID { get; set; }
        public long FileDataID { get; set; }
        public float GeoBoxMinX { get; set; }
        public float GeoBoxMinY { get; set; }
        public float GeoBoxMinZ { get; set; }
        public float GeoBoxMaxX { get; set; }
        public float GeoBoxMaxY { get; set; }
        public float GeoBoxMaxZ { get; set; }
        public float OverrideLootEffectScale { get; set; }
        public float OverrideNameScale { get; set; }
        public int ObjectEffectPackageID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
