//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_event_npc_vendor
    {
        public sbyte eventEntry { get; set; }
        public decimal guid { get; set; }
        public short slot { get; set; }
        public int item { get; set; }
        public int maxcount { get; set; }
        public int incrtime { get; set; }
        public int ExtendedCost { get; set; }
        public byte type { get; set; }
        public string BonusListIDs { get; set; }
        public long PlayerConditionID { get; set; }
        public byte IgnoreFiltering { get; set; }
    }
}
