//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject_template_locale
    {
        public int entry { get; set; }
        public string locale { get; set; }
        public string name { get; set; }
        public string castBarCaption { get; set; }
        public string unk1 { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
