//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_event
    {
        public byte eventEntry { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public decimal occurence { get; set; }
        public decimal length { get; set; }
        public int holiday { get; set; }
        public string description { get; set; }
        public byte world_event { get; set; }
        public Nullable<byte> announce { get; set; }
    }
}
