//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject_template_addon
    {
        public int entry { get; set; }
        public int faction { get; set; }
        public long flags { get; set; }
        public int mingold { get; set; }
        public int maxgold { get; set; }
        public int WorldEffectID { get; set; }
    }
}
