//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_event_condition_save
    {
        public byte eventEntry { get; set; }
        public long condition_id { get; set; }
        public Nullable<float> done { get; set; }
    }
}
