//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject_template
    {
        public int entry { get; set; }
        public byte type { get; set; }
        public int displayId { get; set; }
        public string name { get; set; }
        public string IconName { get; set; }
        public string castBarCaption { get; set; }
        public string unk1 { get; set; }
        public float size { get; set; }
        public int Data0 { get; set; }
        public int Data1 { get; set; }
        public int Data2 { get; set; }
        public int Data3 { get; set; }
        public int Data4 { get; set; }
        public int Data5 { get; set; }
        public int Data6 { get; set; }
        public int Data7 { get; set; }
        public int Data8 { get; set; }
        public int Data9 { get; set; }
        public int Data10 { get; set; }
        public int Data11 { get; set; }
        public int Data12 { get; set; }
        public int Data13 { get; set; }
        public int Data14 { get; set; }
        public int Data15 { get; set; }
        public int Data16 { get; set; }
        public int Data17 { get; set; }
        public int Data18 { get; set; }
        public int Data19 { get; set; }
        public int Data20 { get; set; }
        public int Data21 { get; set; }
        public int Data22 { get; set; }
        public int Data23 { get; set; }
        public int Data24 { get; set; }
        public int Data25 { get; set; }
        public int Data26 { get; set; }
        public int Data27 { get; set; }
        public int Data28 { get; set; }
        public int Data29 { get; set; }
        public int Data30 { get; set; }
        public int Data31 { get; set; }
        public int Data32 { get; set; }
        public int RequiredLevel { get; set; }
        public string AIName { get; set; }
        public string ScriptName { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
