//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gameobject_addon
    {
        public decimal guid { get; set; }
        public float parent_rotation0 { get; set; }
        public float parent_rotation1 { get; set; }
        public float parent_rotation2 { get; set; }
        public float parent_rotation3 { get; set; }
        public byte invisibilityType { get; set; }
        public long invisibilityValue { get; set; }
        public int WorldEffectID { get; set; }
    }
}
