//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_event_quest_condition
    {
        public byte eventEntry { get; set; }
        public int quest { get; set; }
        public int condition_id { get; set; }
        public Nullable<float> num { get; set; }
    }
}
