//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class garr_ability
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public long IconFileDataID { get; set; }
        public int Flags { get; set; }
        public int OtherFactionGarrAbilityID { get; set; }
        public byte GarrAbilityCategoryID { get; set; }
        public byte FollowerTypeID { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
