//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class garr_building
    {
        public long ID { get; set; }
        public long HordeGameObjectID { get; set; }
        public long AllianceGameObjectID { get; set; }
        public string NameAlliance { get; set; }
        public string NameHorde { get; set; }
        public string Description { get; set; }
        public string Tooltip { get; set; }
        public long IconFileDataID { get; set; }
        public int CostCurrencyID { get; set; }
        public int HordeTexPrefixKitID { get; set; }
        public int AllianceTexPrefixKitID { get; set; }
        public int AllianceActivationScenePackageID { get; set; }
        public int HordeActivationScenePackageID { get; set; }
        public int FollowerRequiredGarrAbilityID { get; set; }
        public int FollowerGarrAbilityEffectID { get; set; }
        public short CostMoney { get; set; }
        public byte Unknown { get; set; }
        public byte Type { get; set; }
        public byte Level { get; set; }
        public byte Flags { get; set; }
        public byte MaxShipments { get; set; }
        public byte GarrTypeID { get; set; }
        public int BuildDuration { get; set; }
        public int CostCurrencyAmount { get; set; }
        public int BonusAmount { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
