//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class garr_site_level_plot_inst
    {
        public long ID { get; set; }
        public float LandmarkX { get; set; }
        public float LandmarkY { get; set; }
        public int GarrSiteLevelID { get; set; }
        public byte GarrPlotInstanceID { get; set; }
        public byte Unknown { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
