//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class garr_building_plot_inst
    {
        public float LandmarkOffsetX { get; set; }
        public float LandmarkOffsetY { get; set; }
        public int UiTextureAtlasMemberID { get; set; }
        public int GarrSiteLevelPlotInstID { get; set; }
        public byte GarrBuildingID { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
