//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class garr_class_spec
    {
        public string NameMale { get; set; }
        public string NameFemale { get; set; }
        public string NameGenderless { get; set; }
        public int ClassAtlasID { get; set; }
        public int GarrFollItemSetID { get; set; }
        public byte Limit { get; set; }
        public byte Flags { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
