//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class garrison_plot_finalize_info
    {
        public long garrPlotInstanceId { get; set; }
        public long hordeGameObjectId { get; set; }
        public float hordeX { get; set; }
        public float hordeY { get; set; }
        public float hordeZ { get; set; }
        public float hordeO { get; set; }
        public int hordeAnimKitId { get; set; }
        public long allianceGameObjectId { get; set; }
        public float allianceX { get; set; }
        public float allianceY { get; set; }
        public float allianceZ { get; set; }
        public float allianceO { get; set; }
        public int allianceAnimKitId { get; set; }
    }
}
