//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class garr_site_level
    {
        public long ID { get; set; }
        public float TownHallX { get; set; }
        public float TownHallY { get; set; }
        public int MapID { get; set; }
        public int SiteID { get; set; }
        public int MovieID { get; set; }
        public int UpgradeResourceCost { get; set; }
        public int UpgradeMoneyCost { get; set; }
        public byte Level { get; set; }
        public byte UITextureKitID { get; set; }
        public byte Level2 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
