//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class garr_follower_x_ability
    {
        public long ID { get; set; }
        public int GarrFollowerID { get; set; }
        public int GarrAbilityID { get; set; }
        public byte FactionIndex { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
