//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class garr_plot
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long AllianceConstructionGameObjectID { get; set; }
        public long HordeConstructionGameObjectID { get; set; }
        public byte GarrPlotUICategoryID { get; set; }
        public byte PlotType { get; set; }
        public byte Flags { get; set; }
        public long MinCount { get; set; }
        public long MaxCount { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
