//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class garr_follower
    {
        public long HordeCreatureID { get; set; }
        public long AllianceCreatureID { get; set; }
        public string HordeSourceText { get; set; }
        public string AllianceSourceText { get; set; }
        public long HordePortraitIconID { get; set; }
        public long AlliancePortraitIconID { get; set; }
        public long HordeAddedBroadcastTextID { get; set; }
        public long AllianceAddedBroadcastTextID { get; set; }
        public string Name { get; set; }
        public int HordeGarrFollItemSetID { get; set; }
        public int AllianceGarrFollItemSetID { get; set; }
        public int ItemLevelWeapon { get; set; }
        public int ItemLevelArmor { get; set; }
        public int HordeListPortraitTextureKitID { get; set; }
        public int AllianceListPortraitTextureKitID { get; set; }
        public byte FollowerTypeID { get; set; }
        public byte HordeUiAnimRaceInfoID { get; set; }
        public byte AllianceUiAnimRaceInfoID { get; set; }
        public byte Quality { get; set; }
        public byte HordeGarrClassSpecID { get; set; }
        public byte AllianceGarrClassSpecID { get; set; }
        public byte Level { get; set; }
        public byte Unknown1 { get; set; }
        public byte Flags { get; set; }
        public sbyte Unknown2 { get; set; }
        public sbyte Unknown3 { get; set; }
        public byte GarrTypeID { get; set; }
        public byte MaxDurability { get; set; }
        public byte Class { get; set; }
        public byte HordeFlavorTextGarrStringID { get; set; }
        public byte AllianceFlavorTextGarrStringID { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
