//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gm_complaint_chatlog
    {
        public long complaintId { get; set; }
        public long lineId { get; set; }
        public long timestamp { get; set; }
        public string text { get; set; }
    }
}
