//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gm_complaint
    {
        public long id { get; set; }
        public decimal playerGuid { get; set; }
        public string note { get; set; }
        public long createTime { get; set; }
        public int mapId { get; set; }
        public float posX { get; set; }
        public float posY { get; set; }
        public float posZ { get; set; }
        public float facing { get; set; }
        public decimal targetCharacterGuid { get; set; }
        public int complaintType { get; set; }
        public int reportLineIndex { get; set; }
        public long closedBy { get; set; }
        public decimal assignedTo { get; set; }
        public string comment { get; set; }
    }
}
