//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gossip_menu_option
    {
        public int MenuID { get; set; }
        public int OptionID { get; set; }
        public byte OptionIcon { get; set; }
        public string OptionText { get; set; }
        public long OptionBroadcastTextId { get; set; }
        public long OptionType { get; set; }
        public decimal OptionNpcflag { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
