//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public long guid { get; set; }
        public decimal leaderGuid { get; set; }
        public byte lootMethod { get; set; }
        public decimal looterGuid { get; set; }
        public byte lootThreshold { get; set; }
        public System.Guid icon1 { get; set; }
        public System.Guid icon2 { get; set; }
        public System.Guid icon3 { get; set; }
        public System.Guid icon4 { get; set; }
        public System.Guid icon5 { get; set; }
        public System.Guid icon6 { get; set; }
        public System.Guid icon7 { get; set; }
        public System.Guid icon8 { get; set; }
        public byte groupType { get; set; }
        public byte difficulty { get; set; }
        public byte raidDifficulty { get; set; }
        public byte legacyRaidDifficulty { get; set; }
        public decimal masterLooterGuid { get; set; }
    }
}
