//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_rank
    {
        public decimal guildid { get; set; }
        public byte rid { get; set; }
        public string rname { get; set; }
        public int rights { get; set; }
        public long BankMoneyPerDay { get; set; }
    }
}
