//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_achievement
    {
        public decimal guildId { get; set; }
        public long achievement { get; set; }
        public long date { get; set; }
        public string guids { get; set; }
    }
}
