//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_bank_right
    {
        public decimal guildid { get; set; }
        public byte TabId { get; set; }
        public byte rid { get; set; }
        public sbyte gbright { get; set; }
        public int SlotPerDay { get; set; }
    }
}
