//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_finder_applicant
    {
        public decimal guildId { get; set; }
        public decimal playerGuid { get; set; }
        public Nullable<byte> availability { get; set; }
        public Nullable<byte> classRole { get; set; }
        public Nullable<byte> interests { get; set; }
        public string comment { get; set; }
        public Nullable<long> submitTime { get; set; }
    }
}
