//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_finder_guild_settings
    {
        public decimal guildId { get; set; }
        public byte availability { get; set; }
        public byte classRoles { get; set; }
        public byte interests { get; set; }
        public byte level { get; set; }
        public byte listed { get; set; }
        public string comment { get; set; }
    }
}
