//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_bank_eventlog
    {
        public decimal guildid { get; set; }
        public long LogGuid { get; set; }
        public byte TabId { get; set; }
        public byte EventType { get; set; }
        public decimal PlayerGuid { get; set; }
        public decimal ItemOrMoney { get; set; }
        public int ItemStackCount { get; set; }
        public byte DestTabId { get; set; }
        public long TimeStamp { get; set; }
    }
}
