//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_member_withdraw
    {
        public decimal guid { get; set; }
        public long tab0 { get; set; }
        public long tab1 { get; set; }
        public long tab2 { get; set; }
        public long tab3 { get; set; }
        public long tab4 { get; set; }
        public long tab5 { get; set; }
        public long tab6 { get; set; }
        public long tab7 { get; set; }
        public decimal money { get; set; }
    }
}
