//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class heirloom
    {
        public long ItemID { get; set; }
        public string SourceText { get; set; }
        public long OldItem1 { get; set; }
        public long OldItem2 { get; set; }
        public long NextDifficultyItemID { get; set; }
        public long UpgradeItemID1 { get; set; }
        public long UpgradeItemID2 { get; set; }
        public long UpgradeItemID3 { get; set; }
        public int ItemBonusListID1 { get; set; }
        public int ItemBonusListID2 { get; set; }
        public int ItemBonusListID3 { get; set; }
        public byte Flags { get; set; }
        public byte Source { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
