//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday
    {
        public long ID { get; set; }
        public long Date1 { get; set; }
        public long Date2 { get; set; }
        public long Date3 { get; set; }
        public long Date4 { get; set; }
        public long Date5 { get; set; }
        public long Date6 { get; set; }
        public long Date7 { get; set; }
        public long Date8 { get; set; }
        public long Date9 { get; set; }
        public long Date10 { get; set; }
        public long Date11 { get; set; }
        public long Date12 { get; set; }
        public long Date13 { get; set; }
        public long Date14 { get; set; }
        public long Date15 { get; set; }
        public long Date16 { get; set; }
        public int Duration1 { get; set; }
        public int Duration2 { get; set; }
        public int Duration3 { get; set; }
        public int Duration4 { get; set; }
        public int Duration5 { get; set; }
        public int Duration6 { get; set; }
        public int Duration7 { get; set; }
        public int Duration8 { get; set; }
        public int Duration9 { get; set; }
        public int Duration10 { get; set; }
        public int Region { get; set; }
        public byte Looping { get; set; }
        public byte CalendarFlags1 { get; set; }
        public byte CalendarFlags2 { get; set; }
        public byte CalendarFlags3 { get; set; }
        public byte CalendarFlags4 { get; set; }
        public byte CalendarFlags5 { get; set; }
        public byte CalendarFlags6 { get; set; }
        public byte CalendarFlags7 { get; set; }
        public byte CalendarFlags8 { get; set; }
        public byte CalendarFlags9 { get; set; }
        public byte CalendarFlags10 { get; set; }
        public byte Priority { get; set; }
        public sbyte CalendarFilterType { get; set; }
        public byte Flags { get; set; }
        public long HolidayNameID { get; set; }
        public long HolidayDescriptionID { get; set; }
        public int TextureFileDataID1 { get; set; }
        public int TextureFileDataID2 { get; set; }
        public int TextureFileDataID3 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
