//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotfix_data
    {
        public int Id { get; set; }
        public long TableHash { get; set; }
        public int RecordId { get; set; }
        public Nullable<byte> Deleted { get; set; }
    }
}
