//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class instance
    {
        public long id { get; set; }
        public int map { get; set; }
        public long resettime { get; set; }
        public byte difficulty { get; set; }
        public long completedEncounters { get; set; }
        public string data { get; set; }
        public long entranceId { get; set; }
    }
}
