//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class instance_scenario_progress
    {
        public long id { get; set; }
        public long criteria { get; set; }
        public decimal counter { get; set; }
        public long date { get; set; }
    }
}
