//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip2nationcountries
    {
        public string code { get; set; }
        public string iso_code_2 { get; set; }
        public string iso_code_3 { get; set; }
        public string iso_country { get; set; }
        public string country { get; set; }
        public float lat { get; set; }
        public float lon { get; set; }
    }
}
