//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_search_name
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long Flags1 { get; set; }
        public long Flags2 { get; set; }
        public long Flags3 { get; set; }
        public long AllowableRace { get; set; }
        public long RequiredSpell { get; set; }
        public int RequiredReputationFaction { get; set; }
        public int RequiredSkill { get; set; }
        public int RequiredSkillRank { get; set; }
        public int ItemLevel { get; set; }
        public byte Quality { get; set; }
        public byte RequiredExpansion { get; set; }
        public byte RequiredReputationRank { get; set; }
        public byte RequiredLevel { get; set; }
        public int AllowableClass { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
