//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_instance_artifact_powers
    {
        public decimal itemGuid { get; set; }
        public long artifactPowerId { get; set; }
        public Nullable<byte> purchasedRank { get; set; }
    }
}
