//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_upgrade
    {
        public long ID { get; set; }
        public long CurrencyCost { get; set; }
        public int PrevItemUpgradeID { get; set; }
        public int CurrencyID { get; set; }
        public byte ItemUpgradePathID { get; set; }
        public byte ItemLevelBonus { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
