//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public long ID { get; set; }
        public long FileDataID { get; set; }
        public byte Class { get; set; }
        public byte SubClass { get; set; }
        public sbyte SoundOverrideSubclass { get; set; }
        public sbyte Material { get; set; }
        public byte InventoryType { get; set; }
        public byte Sheath { get; set; }
        public byte GroupSoundsID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
