//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_damage_one_hand
    {
        public long ID { get; set; }
        public float DPS1 { get; set; }
        public float DPS2 { get; set; }
        public float DPS3 { get; set; }
        public float DPS4 { get; set; }
        public float DPS5 { get; set; }
        public float DPS6 { get; set; }
        public float DPS7 { get; set; }
        public int ItemLevel { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
