//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_instance_gems
    {
        public decimal itemGuid { get; set; }
        public long gemItemId1 { get; set; }
        public string gemBonuses1 { get; set; }
        public byte gemContext1 { get; set; }
        public long gemScalingLevel1 { get; set; }
        public long gemItemId2 { get; set; }
        public string gemBonuses2 { get; set; }
        public byte gemContext2 { get; set; }
        public long gemScalingLevel2 { get; set; }
        public long gemItemId3 { get; set; }
        public string gemBonuses3 { get; set; }
        public byte gemContext3 { get; set; }
        public long gemScalingLevel3 { get; set; }
    }
}
