//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_sparse
    {
        public long ID { get; set; }
        public long Flags1 { get; set; }
        public long Flags2 { get; set; }
        public long Flags3 { get; set; }
        public float Unk1 { get; set; }
        public float Unk2 { get; set; }
        public long BuyCount { get; set; }
        public long BuyPrice { get; set; }
        public long SellPrice { get; set; }
        public int AllowableRace { get; set; }
        public long RequiredSpell { get; set; }
        public long MaxCount { get; set; }
        public long Stackable { get; set; }
        public int ItemStatAllocation1 { get; set; }
        public int ItemStatAllocation2 { get; set; }
        public int ItemStatAllocation3 { get; set; }
        public int ItemStatAllocation4 { get; set; }
        public int ItemStatAllocation5 { get; set; }
        public int ItemStatAllocation6 { get; set; }
        public int ItemStatAllocation7 { get; set; }
        public int ItemStatAllocation8 { get; set; }
        public int ItemStatAllocation9 { get; set; }
        public int ItemStatAllocation10 { get; set; }
        public float ItemStatSocketCostMultiplier1 { get; set; }
        public float ItemStatSocketCostMultiplier2 { get; set; }
        public float ItemStatSocketCostMultiplier3 { get; set; }
        public float ItemStatSocketCostMultiplier4 { get; set; }
        public float ItemStatSocketCostMultiplier5 { get; set; }
        public float ItemStatSocketCostMultiplier6 { get; set; }
        public float ItemStatSocketCostMultiplier7 { get; set; }
        public float ItemStatSocketCostMultiplier8 { get; set; }
        public float ItemStatSocketCostMultiplier9 { get; set; }
        public float ItemStatSocketCostMultiplier10 { get; set; }
        public float RangedModRange { get; set; }
        public string Name { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Name4 { get; set; }
        public string Description { get; set; }
        public long BagFamily { get; set; }
        public float ArmorDamageModifier { get; set; }
        public long Duration { get; set; }
        public float StatScalingFactor { get; set; }
        public short AllowableClass { get; set; }
        public int ItemLevel { get; set; }
        public int RequiredSkill { get; set; }
        public int RequiredSkillRank { get; set; }
        public int RequiredReputationFaction { get; set; }
        public short ItemStatValue1 { get; set; }
        public short ItemStatValue2 { get; set; }
        public short ItemStatValue3 { get; set; }
        public short ItemStatValue4 { get; set; }
        public short ItemStatValue5 { get; set; }
        public short ItemStatValue6 { get; set; }
        public short ItemStatValue7 { get; set; }
        public short ItemStatValue8 { get; set; }
        public short ItemStatValue9 { get; set; }
        public short ItemStatValue10 { get; set; }
        public int ScalingStatDistribution { get; set; }
        public int Delay { get; set; }
        public int PageText { get; set; }
        public int StartQuest { get; set; }
        public int LockID { get; set; }
        public int RandomProperty { get; set; }
        public int RandomSuffix { get; set; }
        public int ItemSet { get; set; }
        public int Area { get; set; }
        public int Map { get; set; }
        public int TotemCategory { get; set; }
        public int SocketBonus { get; set; }
        public int GemProperties { get; set; }
        public int ItemLimitCategory { get; set; }
        public int HolidayID { get; set; }
        public int RequiredTransmogHolidayID { get; set; }
        public int ItemNameDescriptionID { get; set; }
        public byte Quality { get; set; }
        public byte InventoryType { get; set; }
        public sbyte RequiredLevel { get; set; }
        public byte RequiredHonorRank { get; set; }
        public byte RequiredCityRank { get; set; }
        public byte RequiredReputationRank { get; set; }
        public byte ContainerSlots { get; set; }
        public sbyte ItemStatType1 { get; set; }
        public sbyte ItemStatType2 { get; set; }
        public sbyte ItemStatType3 { get; set; }
        public sbyte ItemStatType4 { get; set; }
        public sbyte ItemStatType5 { get; set; }
        public sbyte ItemStatType6 { get; set; }
        public sbyte ItemStatType7 { get; set; }
        public sbyte ItemStatType8 { get; set; }
        public sbyte ItemStatType9 { get; set; }
        public sbyte ItemStatType10 { get; set; }
        public byte DamageType { get; set; }
        public byte Bonding { get; set; }
        public byte LanguageID { get; set; }
        public byte PageMaterial { get; set; }
        public sbyte Material { get; set; }
        public byte Sheath { get; set; }
        public byte SocketColor1 { get; set; }
        public byte SocketColor2 { get; set; }
        public byte SocketColor3 { get; set; }
        public byte CurrencySubstitutionID { get; set; }
        public byte CurrencySubstitutionCount { get; set; }
        public byte ArtifactID { get; set; }
        public byte RequiredExpansion { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
