//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_extended_cost
    {
        public long ID { get; set; }
        public long RequiredItem1 { get; set; }
        public long RequiredItem2 { get; set; }
        public long RequiredItem3 { get; set; }
        public long RequiredItem4 { get; set; }
        public long RequiredItem5 { get; set; }
        public long RequiredCurrencyCount1 { get; set; }
        public long RequiredCurrencyCount2 { get; set; }
        public long RequiredCurrencyCount3 { get; set; }
        public long RequiredCurrencyCount4 { get; set; }
        public long RequiredCurrencyCount5 { get; set; }
        public int RequiredItemCount1 { get; set; }
        public int RequiredItemCount2 { get; set; }
        public int RequiredItemCount3 { get; set; }
        public int RequiredItemCount4 { get; set; }
        public int RequiredItemCount5 { get; set; }
        public int RequiredPersonalArenaRating { get; set; }
        public int RequiredCurrency1 { get; set; }
        public int RequiredCurrency2 { get; set; }
        public int RequiredCurrency3 { get; set; }
        public int RequiredCurrency4 { get; set; }
        public int RequiredCurrency5 { get; set; }
        public byte RequiredArenaSlot { get; set; }
        public byte RequiredFactionId { get; set; }
        public byte RequiredFactionStanding { get; set; }
        public byte RequirementFlags { get; set; }
        public byte RequiredAchievement { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
