//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_instance_modifiers
    {
        public decimal itemGuid { get; set; }
        public Nullable<long> fixedScalingLevel { get; set; }
        public Nullable<long> artifactKnowledgeLevel { get; set; }
    }
}
