//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_random_properties
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public int Enchantment1 { get; set; }
        public int Enchantment2 { get; set; }
        public int Enchantment3 { get; set; }
        public int Enchantment4 { get; set; }
        public int Enchantment5 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
