//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_set
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long ItemID1 { get; set; }
        public long ItemID2 { get; set; }
        public long ItemID3 { get; set; }
        public long ItemID4 { get; set; }
        public long ItemID5 { get; set; }
        public long ItemID6 { get; set; }
        public long ItemID7 { get; set; }
        public long ItemID8 { get; set; }
        public long ItemID9 { get; set; }
        public long ItemID10 { get; set; }
        public long ItemID11 { get; set; }
        public long ItemID12 { get; set; }
        public long ItemID13 { get; set; }
        public long ItemID14 { get; set; }
        public long ItemID15 { get; set; }
        public long ItemID16 { get; set; }
        public long ItemID17 { get; set; }
        public int RequiredSkillRank { get; set; }
        public long RequiredSkill { get; set; }
        public long Flags { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
