//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_disenchant_loot
    {
        public long ID { get; set; }
        public int MinItemLevel { get; set; }
        public int MaxItemLevel { get; set; }
        public int RequiredDisenchantSkill { get; set; }
        public byte ItemClass { get; set; }
        public sbyte ItemSubClass { get; set; }
        public byte ItemQuality { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
