//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_instance_transmog
    {
        public decimal itemGuid { get; set; }
        public int itemModifiedAppearanceAllSpecs { get; set; }
        public int itemModifiedAppearanceSpec1 { get; set; }
        public int itemModifiedAppearanceSpec2 { get; set; }
        public int itemModifiedAppearanceSpec3 { get; set; }
        public int itemModifiedAppearanceSpec4 { get; set; }
        public int spellItemEnchantmentAllSpecs { get; set; }
        public int spellItemEnchantmentSpec1 { get; set; }
        public int spellItemEnchantmentSpec2 { get; set; }
        public int spellItemEnchantmentSpec3 { get; set; }
        public int spellItemEnchantmentSpec4 { get; set; }
    }
}
