//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_set_spell
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public int ItemSetID { get; set; }
        public int ChrSpecID { get; set; }
        public byte Threshold { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
