//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_instance
    {
        public decimal guid { get; set; }
        public int itemEntry { get; set; }
        public decimal owner_guid { get; set; }
        public decimal creatorGuid { get; set; }
        public decimal giftCreatorGuid { get; set; }
        public long count { get; set; }
        public int duration { get; set; }
        public string charges { get; set; }
        public int flags { get; set; }
        public string enchantments { get; set; }
        public byte randomPropertyType { get; set; }
        public long randomPropertyId { get; set; }
        public int durability { get; set; }
        public long playedTime { get; set; }
        public string text { get; set; }
        public long transmogrification { get; set; }
        public long upgradeId { get; set; }
        public long enchantIllusion { get; set; }
        public long battlePetSpeciesId { get; set; }
        public long battlePetBreedData { get; set; }
        public int battlePetLevel { get; set; }
        public long battlePetDisplayId { get; set; }
        public byte context { get; set; }
        public string bonusListIDs { get; set; }
    }
}
