//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_bonus_tree_node
    {
        public long ID { get; set; }
        public int BonusTreeID { get; set; }
        public int SubTreeID { get; set; }
        public int BonusListID { get; set; }
        public int ItemLevelSelectorID { get; set; }
        public byte BonusTreeModID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
