//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_loot_items
    {
        public decimal container_id { get; set; }
        public long item_id { get; set; }
        public int item_count { get; set; }
        public bool follow_rules { get; set; }
        public bool ffa { get; set; }
        public bool blocked { get; set; }
        public bool counted { get; set; }
        public bool under_threshold { get; set; }
        public bool needs_quest { get; set; }
        public byte rnd_type { get; set; }
        public long rnd_prop { get; set; }
        public int rnd_suffix { get; set; }
        public byte context { get; set; }
        public string bonus_list_ids { get; set; }
    }
}
