//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_armor_shield
    {
        public long ID { get; set; }
        public float Quality1 { get; set; }
        public float Quality2 { get; set; }
        public float Quality3 { get; set; }
        public float Quality4 { get; set; }
        public float Quality5 { get; set; }
        public float Quality6 { get; set; }
        public float Quality7 { get; set; }
        public int ItemLevel { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
