//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_refund_instance
    {
        public decimal item_guid { get; set; }
        public decimal player_guid { get; set; }
        public decimal paidMoney { get; set; }
        public int paidExtendedCost { get; set; }
    }
}
