//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_bonus
    {
        public long ID { get; set; }
        public int Value1 { get; set; }
        public int Value2 { get; set; }
        public int BonusListID { get; set; }
        public byte Type { get; set; }
        public byte Index { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
