//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_appearance
    {
        public long ID { get; set; }
        public long DisplayID { get; set; }
        public long IconFileDataID { get; set; }
        public long UIOrder { get; set; }
        public byte ObjectComponentSlot { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
