//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_template_addon
    {
        public long Id { get; set; }
        public long FlagsCu { get; set; }
        public byte FoodType { get; set; }
        public long MinMoneyLoot { get; set; }
        public long MaxMoneyLoot { get; set; }
    }
}
