//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lfg_dungeon_rewards
    {
        public long dungeonId { get; set; }
        public byte maxLevel { get; set; }
        public long firstQuestId { get; set; }
        public long otherQuestId { get; set; }
    }
}
