//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lfg_dungeons
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long Flags { get; set; }
        public string Description { get; set; }
        public float MinItemLevel { get; set; }
        public int MaxLevel { get; set; }
        public int TargetLevelMax { get; set; }
        public short MapID { get; set; }
        public int RandomID { get; set; }
        public int ScenarioID { get; set; }
        public int LastBossJournalEncounterID { get; set; }
        public int BonusReputationAmount { get; set; }
        public int MentorItemLevel { get; set; }
        public int PlayerConditionID { get; set; }
        public byte MinLevel { get; set; }
        public byte TargetLevel { get; set; }
        public byte TargetLevelMin { get; set; }
        public byte DifficultyID { get; set; }
        public byte Type { get; set; }
        public byte Faction { get; set; }
        public byte Expansion { get; set; }
        public byte OrderIndex { get; set; }
        public byte GroupID { get; set; }
        public byte CountTank { get; set; }
        public byte CountHealer { get; set; }
        public byte CountDamage { get; set; }
        public byte MinCountTank { get; set; }
        public byte MinCountHealer { get; set; }
        public byte MinCountDamage { get; set; }
        public byte SubType { get; set; }
        public byte MentorCharLevel { get; set; }
        public int TextureFileDataID { get; set; }
        public int RewardIconFileDataID { get; set; }
        public int ProposalTextureFileDataID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
