//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class light
    {
        public long ID { get; set; }
        public float PosX { get; set; }
        public float PosY { get; set; }
        public float PosZ { get; set; }
        public float FalloffStart { get; set; }
        public float FalloffEnd { get; set; }
        public int MapID { get; set; }
        public int LightParamsID1 { get; set; }
        public int LightParamsID2 { get; set; }
        public int LightParamsID3 { get; set; }
        public int LightParamsID4 { get; set; }
        public int LightParamsID5 { get; set; }
        public int LightParamsID6 { get; set; }
        public int LightParamsID7 { get; set; }
        public int LightParamsID8 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
