//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class liquid_type
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long SpellID { get; set; }
        public float MaxDarkenDepth { get; set; }
        public float FogDarkenIntensity { get; set; }
        public float AmbDarkenIntensity { get; set; }
        public float DirDarkenIntensity { get; set; }
        public float ParticleScale { get; set; }
        public string Texture1 { get; set; }
        public string Texture2 { get; set; }
        public string Texture3 { get; set; }
        public string Texture4 { get; set; }
        public string Texture5 { get; set; }
        public string Texture6 { get; set; }
        public long Color1 { get; set; }
        public long Color2 { get; set; }
        public float Float1 { get; set; }
        public float Float2 { get; set; }
        public float Float3 { get; set; }
        public float Float4 { get; set; }
        public float Float5 { get; set; }
        public float Float6 { get; set; }
        public float Float7 { get; set; }
        public float Float8 { get; set; }
        public float Float9 { get; set; }
        public float Float10 { get; set; }
        public float Float11 { get; set; }
        public float Float12 { get; set; }
        public float Float13 { get; set; }
        public float Float14 { get; set; }
        public float Float15 { get; set; }
        public float Float16 { get; set; }
        public float Float17 { get; set; }
        public float Float18 { get; set; }
        public long Int1 { get; set; }
        public long Int2 { get; set; }
        public long Int3 { get; set; }
        public long Int4 { get; set; }
        public int Flags { get; set; }
        public int LightID { get; set; }
        public byte Type { get; set; }
        public byte ParticleMovement { get; set; }
        public byte ParticleTexSlots { get; set; }
        public byte MaterialID { get; set; }
        public byte DepthTexCount1 { get; set; }
        public byte DepthTexCount2 { get; set; }
        public byte DepthTexCount3 { get; set; }
        public byte DepthTexCount4 { get; set; }
        public byte DepthTexCount5 { get; set; }
        public byte DepthTexCount6 { get; set; }
        public long SoundID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
