//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class @lock
    {
        public long ID { get; set; }
        public long Index1 { get; set; }
        public long Index2 { get; set; }
        public long Index3 { get; set; }
        public long Index4 { get; set; }
        public long Index5 { get; set; }
        public long Index6 { get; set; }
        public long Index7 { get; set; }
        public long Index8 { get; set; }
        public int Skill1 { get; set; }
        public int Skill2 { get; set; }
        public int Skill3 { get; set; }
        public int Skill4 { get; set; }
        public int Skill5 { get; set; }
        public int Skill6 { get; set; }
        public int Skill7 { get; set; }
        public int Skill8 { get; set; }
        public byte Type1 { get; set; }
        public byte Type2 { get; set; }
        public byte Type3 { get; set; }
        public byte Type4 { get; set; }
        public byte Type5 { get; set; }
        public byte Type6 { get; set; }
        public byte Type7 { get; set; }
        public byte Type8 { get; set; }
        public byte Action1 { get; set; }
        public byte Action2 { get; set; }
        public byte Action3 { get; set; }
        public byte Action4 { get; set; }
        public byte Action5 { get; set; }
        public byte Action6 { get; set; }
        public byte Action7 { get; set; }
        public byte Action8 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
