//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mount
    {
        public long SpellId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SourceDescription { get; set; }
        public float CameraPivotMultiplier { get; set; }
        public int MountTypeId { get; set; }
        public int Flags { get; set; }
        public byte Source { get; set; }
        public long ID { get; set; }
        public long PlayerConditionId { get; set; }
        public int UiModelSceneID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
