//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        public long ID { get; set; }
        public long AudioFileDataID { get; set; }
        public long SubtitleFileDataID { get; set; }
        public byte Volume { get; set; }
        public byte KeyID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
