//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_text
    {
        public int ID { get; set; }
        public float Probability0 { get; set; }
        public float Probability1 { get; set; }
        public float Probability2 { get; set; }
        public float Probability3 { get; set; }
        public float Probability4 { get; set; }
        public float Probability5 { get; set; }
        public float Probability6 { get; set; }
        public float Probability7 { get; set; }
        public int BroadcastTextID0 { get; set; }
        public int BroadcastTextID1 { get; set; }
        public int BroadcastTextID2 { get; set; }
        public int BroadcastTextID3 { get; set; }
        public int BroadcastTextID4 { get; set; }
        public int BroadcastTextID5 { get; set; }
        public int BroadcastTextID6 { get; set; }
        public int BroadcastTextID7 { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
