//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class override_spell_data
    {
        public long ID { get; set; }
        public long SpellID1 { get; set; }
        public long SpellID2 { get; set; }
        public long SpellID3 { get; set; }
        public long SpellID4 { get; set; }
        public long SpellID5 { get; set; }
        public long SpellID6 { get; set; }
        public long SpellID7 { get; set; }
        public long SpellID8 { get; set; }
        public long SpellID9 { get; set; }
        public long SpellID10 { get; set; }
        public long PlayerActionbarFileDataID { get; set; }
        public byte Flags { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
