//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_text
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public int NextPageID { get; set; }
        public int PlayerConditionID { get; set; }
        public byte Flags { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
