//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class passportEntities : DbContext
    {
        public passportEntities()
            : base("name=passportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> accounts { get; set; }
        public DbSet<account_access> account_access { get; set; }
        public DbSet<account_banned> account_banned { get; set; }
        public DbSet<account_last_played_character> account_last_played_character { get; set; }
        public DbSet<account_muted> account_muted { get; set; }
        public DbSet<autobroadcast> autobroadcasts { get; set; }
        public DbSet<battle_pet_slots> battle_pet_slots { get; set; }
        public DbSet<battle_pets> battle_pets { get; set; }
        public DbSet<battlenet_account_bans> battlenet_account_bans { get; set; }
        public DbSet<battlenet_account_heirlooms> battlenet_account_heirlooms { get; set; }
        public DbSet<battlenet_account_mounts> battlenet_account_mounts { get; set; }
        public DbSet<battlenet_account_toys> battlenet_account_toys { get; set; }
        public DbSet<battlenet_accounts> battlenet_accounts { get; set; }
        public DbSet<battlenet_item_appearances> battlenet_item_appearances { get; set; }
        public DbSet<battlenet_item_favorite_appearances> battlenet_item_favorite_appearances { get; set; }
        public DbSet<ip_banned> ip_banned { get; set; }
        public DbSet<ip2nationcountries> ip2nationcountries { get; set; }
        public DbSet<logs_ip_actions> logs_ip_actions { get; set; }
        public DbSet<rbac_account_permissions> rbac_account_permissions { get; set; }
        public DbSet<rbac_default_permissions> rbac_default_permissions { get; set; }
        public DbSet<rbac_permissions> rbac_permissions { get; set; }
        public DbSet<realmcharacter> realmcharacters { get; set; }
        public DbSet<realmlist> realmlists { get; set; }
        public DbSet<update> updates { get; set; }
        public DbSet<updates_include> updates_include { get; set; }
        public DbSet<uptime> uptimes { get; set; }
        public DbSet<ip2nation> ip2nation { get; set; }
        public DbSet<log> logs { get; set; }
    }
}
