//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet_aura_effect
    {
        public long guid { get; set; }
        public System.Guid casterGuid { get; set; }
        public long spell { get; set; }
        public long effectMask { get; set; }
        public byte effectIndex { get; set; }
        public int amount { get; set; }
        public int baseAmount { get; set; }
    }
}
