//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_condition
    {
        public long ID { get; set; }
        public long RaceMask { get; set; }
        public long SkillLogic { get; set; }
        public long ReputationLogic { get; set; }
        public long PrevQuestLogic { get; set; }
        public long CurrQuestLogic { get; set; }
        public long CurrentCompletedQuestLogic { get; set; }
        public long SpellLogic { get; set; }
        public long ItemLogic { get; set; }
        public long Time1 { get; set; }
        public long Time2 { get; set; }
        public long AuraSpellLogic { get; set; }
        public long AuraSpellID1 { get; set; }
        public long AuraSpellID2 { get; set; }
        public long AuraSpellID3 { get; set; }
        public long AuraSpellID4 { get; set; }
        public long AchievementLogic { get; set; }
        public long AreaLogic { get; set; }
        public long QuestKillLogic { get; set; }
        public string FailureDescription { get; set; }
        public int MinLevel { get; set; }
        public int MaxLevel { get; set; }
        public int SkillID1 { get; set; }
        public int SkillID2 { get; set; }
        public int SkillID3 { get; set; }
        public int SkillID4 { get; set; }
        public short MinSkill1 { get; set; }
        public short MinSkill2 { get; set; }
        public short MinSkill3 { get; set; }
        public short MinSkill4 { get; set; }
        public short MaxSkill1 { get; set; }
        public short MaxSkill2 { get; set; }
        public short MaxSkill3 { get; set; }
        public short MaxSkill4 { get; set; }
        public int MaxFactionID { get; set; }
        public int PrevQuestID1 { get; set; }
        public int PrevQuestID2 { get; set; }
        public int PrevQuestID3 { get; set; }
        public int PrevQuestID4 { get; set; }
        public int CurrQuestID1 { get; set; }
        public int CurrQuestID2 { get; set; }
        public int CurrQuestID3 { get; set; }
        public int CurrQuestID4 { get; set; }
        public int CurrentCompletedQuestID1 { get; set; }
        public int CurrentCompletedQuestID2 { get; set; }
        public int CurrentCompletedQuestID3 { get; set; }
        public int CurrentCompletedQuestID4 { get; set; }
        public int Explored1 { get; set; }
        public int Explored2 { get; set; }
        public int WorldStateExpressionID { get; set; }
        public int Achievement1 { get; set; }
        public int Achievement2 { get; set; }
        public int Achievement3 { get; set; }
        public int Achievement4 { get; set; }
        public int AreaID1 { get; set; }
        public int AreaID2 { get; set; }
        public int AreaID3 { get; set; }
        public int AreaID4 { get; set; }
        public int QuestKillID { get; set; }
        public int PhaseID { get; set; }
        public int MinAvgEquippedItemLevel { get; set; }
        public int MaxAvgEquippedItemLevel { get; set; }
        public int ModifierTreeID { get; set; }
        public byte Flags { get; set; }
        public sbyte Gender { get; set; }
        public sbyte NativeGender { get; set; }
        public byte MinLanguage { get; set; }
        public byte MaxLanguage { get; set; }
        public byte MinReputation1 { get; set; }
        public byte MinReputation2 { get; set; }
        public byte MinReputation3 { get; set; }
        public byte MaxReputation { get; set; }
        public byte Unknown1 { get; set; }
        public byte MinPVPRank { get; set; }
        public byte MaxPVPRank { get; set; }
        public byte PvpMedal { get; set; }
        public byte ItemFlags { get; set; }
        public byte AuraCount1 { get; set; }
        public byte AuraCount2 { get; set; }
        public byte AuraCount3 { get; set; }
        public byte AuraCount4 { get; set; }
        public byte WeatherID { get; set; }
        public byte PartyStatus { get; set; }
        public byte LifetimeMaxPVPRank { get; set; }
        public byte LfgStatus1 { get; set; }
        public byte LfgStatus2 { get; set; }
        public byte LfgStatus3 { get; set; }
        public byte LfgStatus4 { get; set; }
        public byte LfgCompare1 { get; set; }
        public byte LfgCompare2 { get; set; }
        public byte LfgCompare3 { get; set; }
        public byte LfgCompare4 { get; set; }
        public byte CurrencyCount1 { get; set; }
        public byte CurrencyCount2 { get; set; }
        public byte CurrencyCount3 { get; set; }
        public byte CurrencyCount4 { get; set; }
        public sbyte MinExpansionLevel { get; set; }
        public sbyte MaxExpansionLevel { get; set; }
        public sbyte MinExpansionTier { get; set; }
        public sbyte MaxExpansionTier { get; set; }
        public byte MinGuildLevel { get; set; }
        public byte MaxGuildLevel { get; set; }
        public byte PhaseUseFlags { get; set; }
        public sbyte ChrSpecializationIndex { get; set; }
        public sbyte ChrSpecializationRole { get; set; }
        public sbyte PowerType { get; set; }
        public sbyte PowerTypeComp { get; set; }
        public sbyte PowerTypeValue { get; set; }
        public int ClassMask { get; set; }
        public long LanguageID { get; set; }
        public long MinFactionID1 { get; set; }
        public long MinFactionID2 { get; set; }
        public long MinFactionID3 { get; set; }
        public long SpellID1 { get; set; }
        public long SpellID2 { get; set; }
        public long SpellID3 { get; set; }
        public long SpellID4 { get; set; }
        public long ItemID1 { get; set; }
        public long ItemID2 { get; set; }
        public long ItemID3 { get; set; }
        public long ItemID4 { get; set; }
        public long ItemCount1 { get; set; }
        public long ItemCount2 { get; set; }
        public long ItemCount3 { get; set; }
        public long ItemCount4 { get; set; }
        public long LfgLogic { get; set; }
        public long LfgValue1 { get; set; }
        public long LfgValue2 { get; set; }
        public long LfgValue3 { get; set; }
        public long LfgValue4 { get; set; }
        public long CurrencyLogic { get; set; }
        public long CurrencyID1 { get; set; }
        public long CurrencyID2 { get; set; }
        public long CurrencyID3 { get; set; }
        public long CurrencyID4 { get; set; }
        public long QuestKillMonster1 { get; set; }
        public long QuestKillMonster2 { get; set; }
        public long QuestKillMonster3 { get; set; }
        public long QuestKillMonster4 { get; set; }
        public long QuestKillMonster5 { get; set; }
        public long QuestKillMonster6 { get; set; }
        public long PhaseGroupID { get; set; }
        public long MinAvgItemLevel { get; set; }
        public long MaxAvgItemLevel { get; set; }
        public int MovementFlags1 { get; set; }
        public int MovementFlags2 { get; set; }
        public long MainHandItemSubclassMask { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
