//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class playercreateinfo_cast_spell
    {
        public long raceMask { get; set; }
        public long classMask { get; set; }
        public int spell { get; set; }
        public string note { get; set; }
    }
}
