//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_levelstats
    {
        public byte race { get; set; }
        public byte @class { get; set; }
        public byte level { get; set; }
        public int str { get; set; }
        public int agi { get; set; }
        public int sta { get; set; }
        public int inte { get; set; }
    }
}
