//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class playercreateinfo_spell_custom
    {
        public long racemask { get; set; }
        public long classmask { get; set; }
        public int Spell { get; set; }
        public string Note { get; set; }
    }
}
