//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class points_of_interest
    {
        public int ID { get; set; }
        public float PositionX { get; set; }
        public float PositionY { get; set; }
        public int Icon { get; set; }
        public int Flags { get; set; }
        public int Importance { get; set; }
        public string Name { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
