//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class power_type
    {
        public long ID { get; set; }
        public string PowerTypeToken { get; set; }
        public string PowerCostToken { get; set; }
        public float RegenerationPeace { get; set; }
        public float RegenerationCombat { get; set; }
        public short MaxPower { get; set; }
        public int RegenerationDelay { get; set; }
        public int Flags { get; set; }
        public byte PowerTypeEnum { get; set; }
        public sbyte RegenerationMin { get; set; }
        public sbyte RegenerationCenter { get; set; }
        public sbyte RegenerationMax { get; set; }
        public byte UIModifier { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
