//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvpstats_players
    {
        public decimal battleground_id { get; set; }
        public decimal character_guid { get; set; }
        public bool winner { get; set; }
        public int score_killing_blows { get; set; }
        public int score_deaths { get; set; }
        public int score_honorable_kills { get; set; }
        public int score_bonus_honor { get; set; }
        public int score_damage_done { get; set; }
        public int score_healing_done { get; set; }
        public int attr_1 { get; set; }
        public int attr_2 { get; set; }
        public int attr_3 { get; set; }
        public int attr_4 { get; set; }
        public int attr_5 { get; set; }
    }
}
