//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvpstats_battlegrounds
    {
        public decimal id { get; set; }
        public sbyte winner_faction { get; set; }
        public byte bracket_id { get; set; }
        public byte type { get; set; }
        public System.DateTime date { get; set; }
    }
}
