//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_details
    {
        public int ID { get; set; }
        public int Emote1 { get; set; }
        public int Emote2 { get; set; }
        public int Emote3 { get; set; }
        public int Emote4 { get; set; }
        public long EmoteDelay1 { get; set; }
        public long EmoteDelay2 { get; set; }
        public long EmoteDelay3 { get; set; }
        public long EmoteDelay4 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
