//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_objectives_locale
    {
        public int ID { get; set; }
        public string locale { get; set; }
        public int QuestId { get; set; }
        public sbyte StorageIndex { get; set; }
        public string Description { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
