//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_template_addon
    {
        public int ID { get; set; }
        public byte MaxLevel { get; set; }
        public long AllowableClasses { get; set; }
        public int SourceSpellID { get; set; }
        public int PrevQuestID { get; set; }
        public int NextQuestID { get; set; }
        public int ExclusiveGroup { get; set; }
        public int RewardMailTemplateID { get; set; }
        public long RewardMailDelay { get; set; }
        public int RequiredSkillID { get; set; }
        public int RequiredSkillPoints { get; set; }
        public int RequiredMinRepFaction { get; set; }
        public int RequiredMaxRepFaction { get; set; }
        public int RequiredMinRepValue { get; set; }
        public int RequiredMaxRepValue { get; set; }
        public byte ProvidedItemCount { get; set; }
        public byte SpecialFlags { get; set; }
        public string ScriptName { get; set; }
    }
}
