//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_tracker
    {
        public int id { get; set; }
        public decimal character_guid { get; set; }
        public System.DateTime quest_accept_time { get; set; }
        public Nullable<System.DateTime> quest_complete_time { get; set; }
        public Nullable<System.DateTime> quest_abandon_time { get; set; }
        public bool completed_by_gm { get; set; }
        public string core_hash { get; set; }
        public string core_revision { get; set; }
    }
}
