//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_template
    {
        public long ID { get; set; }
        public byte QuestType { get; set; }
        public int QuestLevel { get; set; }
        public long QuestPackageID { get; set; }
        public int MinLevel { get; set; }
        public short QuestSortID { get; set; }
        public int QuestInfoID { get; set; }
        public byte SuggestedGroupNum { get; set; }
        public long RewardNextQuest { get; set; }
        public long RewardXPDifficulty { get; set; }
        public float RewardXPMultiplier { get; set; }
        public int RewardMoney { get; set; }
        public long RewardMoneyDifficulty { get; set; }
        public float RewardMoneyMultiplier { get; set; }
        public long RewardBonusMoney { get; set; }
        public long RewardDisplaySpell1 { get; set; }
        public long RewardDisplaySpell2 { get; set; }
        public long RewardDisplaySpell3 { get; set; }
        public long RewardSpell { get; set; }
        public long RewardHonor { get; set; }
        public long RewardKillHonor { get; set; }
        public long StartItem { get; set; }
        public long RewardArtifactXPDifficulty { get; set; }
        public float RewardArtifactXPMultiplier { get; set; }
        public long RewardArtifactCategoryID { get; set; }
        public long Flags { get; set; }
        public long FlagsEx { get; set; }
        public long RewardItem1 { get; set; }
        public long RewardAmount1 { get; set; }
        public long RewardItem2 { get; set; }
        public long RewardAmount2 { get; set; }
        public long RewardItem3 { get; set; }
        public long RewardAmount3 { get; set; }
        public long RewardItem4 { get; set; }
        public long RewardAmount4 { get; set; }
        public long ItemDrop1 { get; set; }
        public long ItemDropQuantity1 { get; set; }
        public long ItemDrop2 { get; set; }
        public long ItemDropQuantity2 { get; set; }
        public long ItemDrop3 { get; set; }
        public long ItemDropQuantity3 { get; set; }
        public long ItemDrop4 { get; set; }
        public long ItemDropQuantity4 { get; set; }
        public long RewardChoiceItemID1 { get; set; }
        public long RewardChoiceItemQuantity1 { get; set; }
        public long RewardChoiceItemDisplayID1 { get; set; }
        public long RewardChoiceItemID2 { get; set; }
        public long RewardChoiceItemQuantity2 { get; set; }
        public long RewardChoiceItemDisplayID2 { get; set; }
        public long RewardChoiceItemID3 { get; set; }
        public long RewardChoiceItemQuantity3 { get; set; }
        public long RewardChoiceItemDisplayID3 { get; set; }
        public long RewardChoiceItemID4 { get; set; }
        public long RewardChoiceItemQuantity4 { get; set; }
        public long RewardChoiceItemDisplayID4 { get; set; }
        public long RewardChoiceItemID5 { get; set; }
        public long RewardChoiceItemQuantity5 { get; set; }
        public long RewardChoiceItemDisplayID5 { get; set; }
        public long RewardChoiceItemID6 { get; set; }
        public long RewardChoiceItemQuantity6 { get; set; }
        public long RewardChoiceItemDisplayID6 { get; set; }
        public long POIContinent { get; set; }
        public float POIx { get; set; }
        public float POIy { get; set; }
        public int POIPriority { get; set; }
        public long RewardTitle { get; set; }
        public long RewardArenaPoints { get; set; }
        public long RewardSkillLineID { get; set; }
        public long RewardNumSkillUps { get; set; }
        public long PortraitGiver { get; set; }
        public long PortraitTurnIn { get; set; }
        public long RewardFactionID1 { get; set; }
        public int RewardFactionValue1 { get; set; }
        public int RewardFactionOverride1 { get; set; }
        public long RewardFactionCapIn1 { get; set; }
        public long RewardFactionID2 { get; set; }
        public int RewardFactionValue2 { get; set; }
        public int RewardFactionOverride2 { get; set; }
        public long RewardFactionCapIn2 { get; set; }
        public long RewardFactionID3 { get; set; }
        public int RewardFactionValue3 { get; set; }
        public int RewardFactionOverride3 { get; set; }
        public long RewardFactionCapIn3 { get; set; }
        public long RewardFactionID4 { get; set; }
        public int RewardFactionValue4 { get; set; }
        public int RewardFactionOverride4 { get; set; }
        public long RewardFactionCapIn4 { get; set; }
        public long RewardFactionID5 { get; set; }
        public int RewardFactionValue5 { get; set; }
        public int RewardFactionOverride5 { get; set; }
        public long RewardFactionCapIn5 { get; set; }
        public long RewardFactionFlags { get; set; }
        public long RewardCurrencyID1 { get; set; }
        public long RewardCurrencyQty1 { get; set; }
        public long RewardCurrencyID2 { get; set; }
        public long RewardCurrencyQty2 { get; set; }
        public long RewardCurrencyID3 { get; set; }
        public long RewardCurrencyQty3 { get; set; }
        public long RewardCurrencyID4 { get; set; }
        public long RewardCurrencyQty4 { get; set; }
        public long AcceptedSoundKitID { get; set; }
        public long CompleteSoundKitID { get; set; }
        public long AreaGroupID { get; set; }
        public long TimeAllowed { get; set; }
        public int AllowableRaces { get; set; }
        public long QuestRewardID { get; set; }
        public int Expansion { get; set; }
        public string LogTitle { get; set; }
        public string LogDescription { get; set; }
        public string QuestDescription { get; set; }
        public string AreaDescription { get; set; }
        public string PortraitGiverText { get; set; }
        public string PortraitGiverName { get; set; }
        public string PortraitTurnInText { get; set; }
        public string PortraitTurnInName { get; set; }
        public string QuestCompletionLog { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
