//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_objectives
    {
        public int ID { get; set; }
        public int QuestID { get; set; }
        public byte Type { get; set; }
        public byte Order { get; set; }
        public sbyte StorageIndex { get; set; }
        public int ObjectID { get; set; }
        public int Amount { get; set; }
        public long Flags { get; set; }
        public long Flags2 { get; set; }
        public float ProgressBarWeight { get; set; }
        public string Description { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
