//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_xp
    {
        public long ID { get; set; }
        public int Exp1 { get; set; }
        public int Exp2 { get; set; }
        public int Exp3 { get; set; }
        public int Exp4 { get; set; }
        public int Exp5 { get; set; }
        public int Exp6 { get; set; }
        public int Exp7 { get; set; }
        public int Exp8 { get; set; }
        public int Exp9 { get; set; }
        public int Exp10 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
