//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_request_items
    {
        public int ID { get; set; }
        public int EmoteOnComplete { get; set; }
        public int EmoteOnIncomplete { get; set; }
        public long EmoteOnCompleteDelay { get; set; }
        public long EmoteOnIncompleteDelay { get; set; }
        public string CompletionText { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
