//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_faction_reward
    {
        public long ID { get; set; }
        public short QuestRewFactionValue1 { get; set; }
        public short QuestRewFactionValue2 { get; set; }
        public short QuestRewFactionValue3 { get; set; }
        public short QuestRewFactionValue4 { get; set; }
        public short QuestRewFactionValue5 { get; set; }
        public short QuestRewFactionValue6 { get; set; }
        public short QuestRewFactionValue7 { get; set; }
        public short QuestRewFactionValue8 { get; set; }
        public short QuestRewFactionValue9 { get; set; }
        public short QuestRewFactionValue10 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
