//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_package_item
    {
        public long ID { get; set; }
        public long ItemID { get; set; }
        public int QuestPackageID { get; set; }
        public byte FilterType { get; set; }
        public long ItemCount { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
