//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_template_locale
    {
        public int ID { get; set; }
        public string locale { get; set; }
        public string LogTitle { get; set; }
        public string LogDescription { get; set; }
        public string QuestDescription { get; set; }
        public string AreaDescription { get; set; }
        public string PortraitGiverText { get; set; }
        public string PortraitGiverName { get; set; }
        public string PortraitTurnInText { get; set; }
        public string PortraitTurnInName { get; set; }
        public string QuestCompletionLog { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
