//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_poi_points
    {
        public int QuestID { get; set; }
        public int Idx1 { get; set; }
        public int Idx2 { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
