//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_money_reward
    {
        public long ID { get; set; }
        public long Money1 { get; set; }
        public long Money2 { get; set; }
        public long Money3 { get; set; }
        public long Money4 { get; set; }
        public long Money5 { get; set; }
        public long Money6 { get; set; }
        public long Money7 { get; set; }
        public long Money8 { get; set; }
        public long Money9 { get; set; }
        public long Money10 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
