//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rand_prop_points
    {
        public long ID { get; set; }
        public long EpicPropertiesPoints1 { get; set; }
        public long EpicPropertiesPoints2 { get; set; }
        public long EpicPropertiesPoints3 { get; set; }
        public long EpicPropertiesPoints4 { get; set; }
        public long EpicPropertiesPoints5 { get; set; }
        public long RarePropertiesPoints1 { get; set; }
        public long RarePropertiesPoints2 { get; set; }
        public long RarePropertiesPoints3 { get; set; }
        public long RarePropertiesPoints4 { get; set; }
        public long RarePropertiesPoints5 { get; set; }
        public long UncommonPropertiesPoints1 { get; set; }
        public long UncommonPropertiesPoints2 { get; set; }
        public long UncommonPropertiesPoints3 { get; set; }
        public long UncommonPropertiesPoints4 { get; set; }
        public long UncommonPropertiesPoints5 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
