//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rbac_permissions
    {
        public rbac_permissions()
        {
            this.rbac_account_permissions = new HashSet<rbac_account_permissions>();
            this.rbac_default_permissions = new HashSet<rbac_default_permissions>();
            this.rbac_permissions1 = new HashSet<rbac_permissions>();
            this.rbac_permissions2 = new HashSet<rbac_permissions>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<rbac_account_permissions> rbac_account_permissions { get; set; }
        public virtual ICollection<rbac_default_permissions> rbac_default_permissions { get; set; }
        public virtual ICollection<rbac_permissions> rbac_permissions1 { get; set; }
        public virtual ICollection<rbac_permissions> rbac_permissions2 { get; set; }
    }
}
