//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class scenario_step
    {
        public long ID { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int CriteriaTreeID { get; set; }
        public int ScenarioID { get; set; }
        public int PreviousStepID { get; set; }
        public int QuestRewardID { get; set; }
        public byte Step { get; set; }
        public byte Flags { get; set; }
        public long BonusRequiredStepID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
