//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class scenario
    {
        public long map { get; set; }
        public byte difficulty { get; set; }
        public long scenario_A { get; set; }
        public long scenario_H { get; set; }
    }
}
