//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class scenario_poi
    {
        public int CriteriaTreeID { get; set; }
        public int BlobIndex { get; set; }
        public int Idx1 { get; set; }
        public int MapID { get; set; }
        public int WorldMapAreaId { get; set; }
        public int Floor { get; set; }
        public int Priority { get; set; }
        public int Flags { get; set; }
        public int WorldEffectID { get; set; }
        public int PlayerConditionID { get; set; }
        public Nullable<short> VerifiedBuild { get; set; }
    }
}
