//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill_line
    {
        public long ID { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string AlternateVerb { get; set; }
        public int Flags { get; set; }
        public byte CategoryID { get; set; }
        public byte CanLink { get; set; }
        public long IconFileDataID { get; set; }
        public long ParentSkillLineID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
