//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill_tiers
    {
        public long ID { get; set; }
        public long Value1 { get; set; }
        public long Value2 { get; set; }
        public long Value3 { get; set; }
        public long Value4 { get; set; }
        public long Value5 { get; set; }
        public long Value6 { get; set; }
        public long Value7 { get; set; }
        public long Value8 { get; set; }
        public long Value9 { get; set; }
        public long Value10 { get; set; }
        public long Value11 { get; set; }
        public long Value12 { get; set; }
        public long Value13 { get; set; }
        public long Value14 { get; set; }
        public long Value15 { get; set; }
        public long Value16 { get; set; }
    }
}
