//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill_line_ability
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public long RaceMask { get; set; }
        public long SupercedesSpell { get; set; }
        public int SkillLine { get; set; }
        public int MinSkillLineRank { get; set; }
        public int TrivialSkillLineRankHigh { get; set; }
        public int TrivialSkillLineRankLow { get; set; }
        public int UniqueBit { get; set; }
        public int TradeSkillCategoryID { get; set; }
        public byte AcquireMethod { get; set; }
        public byte NumSkillUps { get; set; }
        public byte Unknown703 { get; set; }
        public int ClassMask { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
