//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill_race_class_info
    {
        public long ID { get; set; }
        public int RaceMask { get; set; }
        public int SkillID { get; set; }
        public int Flags { get; set; }
        public int SkillTierID { get; set; }
        public byte Availability { get; set; }
        public byte MinLevel { get; set; }
        public int ClassMask { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
