//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sound_kit
    {
        public string Name { get; set; }
        public float VolumeFloat { get; set; }
        public float MinDistance { get; set; }
        public float DistanceCutoff { get; set; }
        public float VolumeVariationPlus { get; set; }
        public float VolumeVariationMinus { get; set; }
        public float PitchVariationPlus { get; set; }
        public float PitchVariationMinus { get; set; }
        public float PitchAdjust { get; set; }
        public int Flags { get; set; }
        public int SoundEntriesAdvancedID { get; set; }
        public int BusOverwriteID { get; set; }
        public byte SoundType { get; set; }
        public byte EAXDef { get; set; }
        public byte DialogType { get; set; }
        public byte Unk700 { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
