//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialization_spells
    {
        public long SpellID { get; set; }
        public long OverridesSpellID { get; set; }
        public string Description { get; set; }
        public int SpecID { get; set; }
        public byte OrderIndex { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
