//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_item_enchantment_condition
    {
        public long ID { get; set; }
        public byte LTOperandType1 { get; set; }
        public byte LTOperandType2 { get; set; }
        public byte LTOperandType3 { get; set; }
        public byte LTOperandType4 { get; set; }
        public byte LTOperandType5 { get; set; }
        public byte Operator1 { get; set; }
        public byte Operator2 { get; set; }
        public byte Operator3 { get; set; }
        public byte Operator4 { get; set; }
        public byte Operator5 { get; set; }
        public byte RTOperandType1 { get; set; }
        public byte RTOperandType2 { get; set; }
        public byte RTOperandType3 { get; set; }
        public byte RTOperandType4 { get; set; }
        public byte RTOperandType5 { get; set; }
        public byte RTOperand1 { get; set; }
        public byte RTOperand2 { get; set; }
        public byte RTOperand3 { get; set; }
        public byte RTOperand4 { get; set; }
        public byte RTOperand5 { get; set; }
        public byte Logic1 { get; set; }
        public byte Logic2 { get; set; }
        public byte Logic3 { get; set; }
        public byte Logic4 { get; set; }
        public byte Logic5 { get; set; }
        public long LTOperand1 { get; set; }
        public long LTOperand2 { get; set; }
        public long LTOperand3 { get; set; }
        public long LTOperand4 { get; set; }
        public long LTOperand5 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
