//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_procs_per_minute_mod
    {
        public long ID { get; set; }
        public float Coeff { get; set; }
        public int Param { get; set; }
        public byte Type { get; set; }
        public byte SpellProcsPerMinuteID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
