//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_areatrigger
    {
        public long SpellMiscId { get; set; }
        public long AreaTriggerId { get; set; }
        public long MoveCurveId { get; set; }
        public long ScaleCurveId { get; set; }
        public long MorphCurveId { get; set; }
        public long FacingCurveId { get; set; }
        public long DecalPropertiesId { get; set; }
        public long TimeToTarget { get; set; }
        public long TimeToTargetScale { get; set; }
        public long VerifiedBuild { get; set; }
    }
}
