//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_aura_restrictions
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public long CasterAuraSpell { get; set; }
        public long TargetAuraSpell { get; set; }
        public long ExcludeCasterAuraSpell { get; set; }
        public long ExcludeTargetAuraSpell { get; set; }
        public byte DifficultyID { get; set; }
        public byte CasterAuraState { get; set; }
        public byte TargetAuraState { get; set; }
        public byte ExcludeCasterAuraState { get; set; }
        public byte ExcludeTargetAuraState { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
