//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_effect
    {
        public long EffectSpellClassMask1 { get; set; }
        public long EffectSpellClassMask2 { get; set; }
        public long EffectSpellClassMask3 { get; set; }
        public long EffectSpellClassMask4 { get; set; }
        public long ID { get; set; }
        public long SpellID { get; set; }
        public long Effect { get; set; }
        public long EffectAura { get; set; }
        public int EffectBasePoints { get; set; }
        public long EffectIndex { get; set; }
        public int EffectMiscValue { get; set; }
        public int EffectMiscValueB { get; set; }
        public long EffectRadiusIndex { get; set; }
        public long EffectRadiusMaxIndex { get; set; }
        public long ImplicitTarget1 { get; set; }
        public long ImplicitTarget2 { get; set; }
        public long DifficultyID { get; set; }
        public float EffectAmplitude { get; set; }
        public long EffectAuraPeriod { get; set; }
        public float EffectBonusCoefficient { get; set; }
        public float EffectChainAmplitude { get; set; }
        public long EffectChainTargets { get; set; }
        public int EffectDieSides { get; set; }
        public long EffectItemType { get; set; }
        public long EffectMechanic { get; set; }
        public float EffectPointsPerResource { get; set; }
        public float EffectRealPointsPerLevel { get; set; }
        public long EffectTriggerSpell { get; set; }
        public float EffectPosFacing { get; set; }
        public long EffectAttributes { get; set; }
        public float BonusCoefficientFromAP { get; set; }
        public float PvPMultiplier { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
