//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_levels
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public int BaseLevel { get; set; }
        public int MaxLevel { get; set; }
        public int SpellLevel { get; set; }
        public byte DifficultyID { get; set; }
        public byte MaxUsableLevel { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
