//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_reagents
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public int Reagent1 { get; set; }
        public int Reagent2 { get; set; }
        public int Reagent3 { get; set; }
        public int Reagent4 { get; set; }
        public int Reagent5 { get; set; }
        public int Reagent6 { get; set; }
        public int Reagent7 { get; set; }
        public int Reagent8 { get; set; }
        public int ReagentCount1 { get; set; }
        public int ReagentCount2 { get; set; }
        public int ReagentCount3 { get; set; }
        public int ReagentCount4 { get; set; }
        public int ReagentCount5 { get; set; }
        public int ReagentCount6 { get; set; }
        public int ReagentCount7 { get; set; }
        public int ReagentCount8 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
