//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_categories
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public int Category { get; set; }
        public int StartRecoveryCategory { get; set; }
        public int ChargeCategory { get; set; }
        public byte DifficultyID { get; set; }
        public byte DefenseType { get; set; }
        public byte DispelType { get; set; }
        public byte Mechanic { get; set; }
        public byte PreventionType { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
