//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_target_restrictions
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public float ConeAngle { get; set; }
        public float Width { get; set; }
        public long Targets { get; set; }
        public int TargetCreatureType { get; set; }
        public byte DifficultyID { get; set; }
        public byte MaxAffectedTargets { get; set; }
        public long MaxTargetLevel { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
