//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_area
    {
        public int spell { get; set; }
        public int area { get; set; }
        public int quest_start { get; set; }
        public int quest_end { get; set; }
        public int aura_spell { get; set; }
        public long racemask { get; set; }
        public byte gender { get; set; }
        public byte autocast { get; set; }
        public int quest_start_status { get; set; }
        public int quest_end_status { get; set; }
    }
}
