//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_equipped_items
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public int EquippedItemInventoryTypeMask { get; set; }
        public int EquippedItemSubClassMask { get; set; }
        public sbyte EquippedItemClass { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
