//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spelleffect_dbc
    {
        public long Id { get; set; }
        public long Effect { get; set; }
        public long EffectApplyAuraName { get; set; }
        public long EffectAmplitude { get; set; }
        public int EffectBasePoints { get; set; }
        public long EffectChainTarget { get; set; }
        public int EffectDieSides { get; set; }
        public long EffectItemType { get; set; }
        public long EffectMechanic { get; set; }
        public int EffectMiscValue { get; set; }
        public int EffectMiscValueB { get; set; }
        public long EffectRadiusIndex { get; set; }
        public long EffectRadiusIndexMax { get; set; }
        public long EffectSpellClassMaskA { get; set; }
        public long EffectSpellClassMaskB { get; set; }
        public long EffectSpellClassMaskC { get; set; }
        public long EffectTriggerSpell { get; set; }
        public long EffectImplicitTargetA { get; set; }
        public long EffectImplicitTargetB { get; set; }
        public long EffectSpellId { get; set; }
        public long EffectIndex { get; set; }
    }
}
