//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_range
    {
        public long ID { get; set; }
        public float MinRangeHostile { get; set; }
        public float MinRangeFriend { get; set; }
        public float MaxRangeHostile { get; set; }
        public float MaxRangeFriend { get; set; }
        public string DisplayName { get; set; }
        public string DisplayNameShort { get; set; }
        public byte Flags { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
