//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_proc
    {
        public int SpellId { get; set; }
        public byte SchoolMask { get; set; }
        public int SpellFamilyName { get; set; }
        public long SpellFamilyMask0 { get; set; }
        public long SpellFamilyMask1 { get; set; }
        public long SpellFamilyMask2 { get; set; }
        public long SpellFamilyMask3 { get; set; }
        public long ProcFlags { get; set; }
        public long SpellTypeMask { get; set; }
        public long SpellPhaseMask { get; set; }
        public long HitMask { get; set; }
        public long AttributesMask { get; set; }
        public float ProcsPerMinute { get; set; }
        public float Chance { get; set; }
        public long Cooldown { get; set; }
        public byte Charges { get; set; }
    }
}
