//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_class_options
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public long SpellClassMask1 { get; set; }
        public long SpellClassMask2 { get; set; }
        public long SpellClassMask3 { get; set; }
        public long SpellClassMask4 { get; set; }
        public byte SpellClassSet { get; set; }
        public long ModalNextSpell { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
