//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_totems
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public long Totem1 { get; set; }
        public long Totem2 { get; set; }
        public int RequiredTotemCategoryID1 { get; set; }
        public int RequiredTotemCategoryID2 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
