//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_power
    {
        public long SpellID { get; set; }
        public int ManaCost { get; set; }
        public float ManaCostPercentage { get; set; }
        public float ManaCostPercentagePerSecond { get; set; }
        public long RequiredAura { get; set; }
        public float HealthCostPercentage { get; set; }
        public byte PowerIndex { get; set; }
        public byte PowerType { get; set; }
        public long ID { get; set; }
        public int ManaCostPerLevel { get; set; }
        public int ManaCostPerSecond { get; set; }
        public int ManaCostAdditional { get; set; }
        public long PowerDisplayID { get; set; }
        public long UnitPowerBarID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
