//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_shapeshift
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public long ShapeshiftExclude1 { get; set; }
        public long ShapeshiftExclude2 { get; set; }
        public long ShapeshiftMask1 { get; set; }
        public long ShapeshiftMask2 { get; set; }
        public byte StanceBarOrder { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
