//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_shapeshift_form
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public float WeaponDamageVariance { get; set; }
        public long Flags { get; set; }
        public int CombatRoundTime { get; set; }
        public int MountTypeID { get; set; }
        public sbyte CreatureType { get; set; }
        public byte BonusActionBar { get; set; }
        public long AttackIconFileDataID { get; set; }
        public long CreatureDisplayID1 { get; set; }
        public long CreatureDisplayID2 { get; set; }
        public long CreatureDisplayID3 { get; set; }
        public long CreatureDisplayID4 { get; set; }
        public long PresetSpellID1 { get; set; }
        public long PresetSpellID2 { get; set; }
        public long PresetSpellID3 { get; set; }
        public long PresetSpellID4 { get; set; }
        public long PresetSpellID5 { get; set; }
        public long PresetSpellID6 { get; set; }
        public long PresetSpellID7 { get; set; }
        public long PresetSpellID8 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
