//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_misc
    {
        public long ID { get; set; }
        public long Attributes { get; set; }
        public long AttributesEx { get; set; }
        public long AttributesExB { get; set; }
        public long AttributesExC { get; set; }
        public long AttributesExD { get; set; }
        public long AttributesExE { get; set; }
        public long AttributesExF { get; set; }
        public long AttributesExG { get; set; }
        public long AttributesExH { get; set; }
        public long AttributesExI { get; set; }
        public long AttributesExJ { get; set; }
        public long AttributesExK { get; set; }
        public long AttributesExL { get; set; }
        public long AttributesExM { get; set; }
        public float Speed { get; set; }
        public float MultistrikeSpeedMod { get; set; }
        public int CastingTimeIndex { get; set; }
        public int DurationIndex { get; set; }
        public int RangeIndex { get; set; }
        public byte SchoolMask { get; set; }
        public long IconFileDataID { get; set; }
        public long ActiveIconFileDataID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
