//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_dbc
    {
        public long Id { get; set; }
        public long Attributes { get; set; }
        public long AttributesEx { get; set; }
        public long AttributesEx2 { get; set; }
        public long AttributesEx3 { get; set; }
        public long AttributesEx4 { get; set; }
        public long AttributesEx5 { get; set; }
        public long AttributesEx6 { get; set; }
        public long AttributesEx7 { get; set; }
        public long AttributesEx8 { get; set; }
        public long AttributesEx9 { get; set; }
        public long AttributesEx10 { get; set; }
        public long CastingTimeIndex { get; set; }
        public long DurationIndex { get; set; }
        public long RangeIndex { get; set; }
        public long SchoolMask { get; set; }
        public long SpellAuraOptionsId { get; set; }
        public long SpellCastingRequirementsId { get; set; }
        public long SpellCategoriesId { get; set; }
        public long SpellClassOptionsId { get; set; }
        public long SpellEquippedItemsId { get; set; }
        public long SpellLevelsId { get; set; }
        public long SpellTargetRestrictionsId { get; set; }
        public long SpellInterruptsId { get; set; }
        public string Comment { get; set; }
    }
}
