//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_aura_options
    {
        public long ID { get; set; }
        public long SpellID { get; set; }
        public long ProcCharges { get; set; }
        public long ProcTypeMask { get; set; }
        public long ProcCategoryRecovery { get; set; }
        public int CumulativeAura { get; set; }
        public byte DifficultyID { get; set; }
        public byte ProcChance { get; set; }
        public byte SpellProcsPerMinuteID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
