//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_x_spell_visual
    {
        public long SpellID { get; set; }
        public long SpellVisualID { get; set; }
        public long ID { get; set; }
        public float Chance { get; set; }
        public int CasterPlayerConditionID { get; set; }
        public int CasterUnitConditionID { get; set; }
        public int PlayerConditionID { get; set; }
        public int UnitConditionID { get; set; }
        public long IconFileDataID { get; set; }
        public long ActiveIconFileDataID { get; set; }
        public byte Flags { get; set; }
        public byte DifficultyID { get; set; }
        public byte Priority { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
