//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tact_key
    {
        public long ID { get; set; }
        public byte Key1 { get; set; }
        public byte Key2 { get; set; }
        public byte Key3 { get; set; }
        public byte Key4 { get; set; }
        public byte Key5 { get; set; }
        public byte Key6 { get; set; }
        public byte Key7 { get; set; }
        public byte Key8 { get; set; }
        public byte Key9 { get; set; }
        public byte Key10 { get; set; }
        public byte Key11 { get; set; }
        public byte Key12 { get; set; }
        public byte Key13 { get; set; }
        public byte Key14 { get; set; }
        public byte Key15 { get; set; }
        public byte Key16 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
