//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxi_path_node
    {
        public float LocX { get; set; }
        public float LocY { get; set; }
        public float LocZ { get; set; }
        public long Delay { get; set; }
        public int PathID { get; set; }
        public int MapID { get; set; }
        public int ArrivalEventID { get; set; }
        public int DepartureEventID { get; set; }
        public byte NodeIndex { get; set; }
        public byte Flags { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
