//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxi_nodes
    {
        public float PosX { get; set; }
        public float PosY { get; set; }
        public float PosZ { get; set; }
        public string Name { get; set; }
        public long MountCreatureID1 { get; set; }
        public long MountCreatureID2 { get; set; }
        public float MapOffsetX { get; set; }
        public float MapOffsetY { get; set; }
        public int MapID { get; set; }
        public int ConditionID { get; set; }
        public int LearnableIndex { get; set; }
        public byte Flags { get; set; }
        public long ID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
