//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxi_path
    {
        public int From { get; set; }
        public int To { get; set; }
        public long ID { get; set; }
        public long Cost { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
