//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class transport
    {
        public decimal guid { get; set; }
        public int entry { get; set; }
        public string name { get; set; }
        public int phaseid { get; set; }
        public int phasegroup { get; set; }
        public string ScriptName { get; set; }
    }
}
