//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit_power_bar_locale
    {
        public long ID { get; set; }
        public string locale { get; set; }
        public string Name_lang { get; set; }
        public string Cost_lang { get; set; }
        public string OutOfError_lang { get; set; }
        public string ToolTip_lang { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
