//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit_power_bar
    {
        public long ID { get; set; }
        public float RegenerationPeace { get; set; }
        public float RegenerationCombat { get; set; }
        public long FileDataID1 { get; set; }
        public long FileDataID2 { get; set; }
        public long FileDataID3 { get; set; }
        public long FileDataID4 { get; set; }
        public long FileDataID5 { get; set; }
        public long FileDataID6 { get; set; }
        public long Color1 { get; set; }
        public long Color2 { get; set; }
        public long Color3 { get; set; }
        public long Color4 { get; set; }
        public long Color5 { get; set; }
        public long Color6 { get; set; }
        public string Name { get; set; }
        public string Cost { get; set; }
        public string OutOfError { get; set; }
        public string ToolTip { get; set; }
        public float StartInset { get; set; }
        public float EndInset { get; set; }
        public int StartPower { get; set; }
        public int Flags { get; set; }
        public byte CenterPower { get; set; }
        public byte BarType { get; set; }
        public long MinPower { get; set; }
        public long MaxPower { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
