//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_template_accessory
    {
        public int entry { get; set; }
        public int accessory_entry { get; set; }
        public sbyte seat_id { get; set; }
        public byte minion { get; set; }
        public string description { get; set; }
        public byte summontype { get; set; }
        public long summontimer { get; set; }
    }
}
