//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public long ID { get; set; }
        public long Flags { get; set; }
        public float TurnSpeed { get; set; }
        public float PitchSpeed { get; set; }
        public float PitchMin { get; set; }
        public float PitchMax { get; set; }
        public float MouseLookOffsetPitch { get; set; }
        public float CameraFadeDistScalarMin { get; set; }
        public float CameraFadeDistScalarMax { get; set; }
        public float CameraPitchOffset { get; set; }
        public float FacingLimitRight { get; set; }
        public float FacingLimitLeft { get; set; }
        public float MsslTrgtTurnLingering { get; set; }
        public float MsslTrgtPitchLingering { get; set; }
        public float MsslTrgtMouseLingering { get; set; }
        public float MsslTrgtEndOpacity { get; set; }
        public float MsslTrgtArcSpeed { get; set; }
        public float MsslTrgtArcRepeat { get; set; }
        public float MsslTrgtArcWidth { get; set; }
        public float MsslTrgtImpactRadius1 { get; set; }
        public float MsslTrgtImpactRadius2 { get; set; }
        public string MsslTrgtArcTexture { get; set; }
        public string MsslTrgtImpactTexture { get; set; }
        public string MsslTrgtImpactModel1 { get; set; }
        public string MsslTrgtImpactModel2 { get; set; }
        public float CameraYawOffset { get; set; }
        public float MsslTrgtImpactTexRadius { get; set; }
        public int SeatID1 { get; set; }
        public int SeatID2 { get; set; }
        public int SeatID3 { get; set; }
        public int SeatID4 { get; set; }
        public int SeatID5 { get; set; }
        public int SeatID6 { get; set; }
        public int SeatID7 { get; set; }
        public int SeatID8 { get; set; }
        public int VehicleUIIndicatorID { get; set; }
        public int PowerDisplayID1 { get; set; }
        public int PowerDisplayID2 { get; set; }
        public int PowerDisplayID3 { get; set; }
        public byte FlagsB { get; set; }
        public byte UILocomotionType { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
