//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_seat
    {
        public long ID { get; set; }
        public long Flags1 { get; set; }
        public long Flags2 { get; set; }
        public long Flags3 { get; set; }
        public float AttachmentOffsetX { get; set; }
        public float AttachmentOffsetY { get; set; }
        public float AttachmentOffsetZ { get; set; }
        public float EnterPreDelay { get; set; }
        public float EnterSpeed { get; set; }
        public float EnterGravity { get; set; }
        public float EnterMinDuration { get; set; }
        public float EnterMaxDuration { get; set; }
        public float EnterMinArcHeight { get; set; }
        public float EnterMaxArcHeight { get; set; }
        public float ExitPreDelay { get; set; }
        public float ExitSpeed { get; set; }
        public float ExitGravity { get; set; }
        public float ExitMinDuration { get; set; }
        public float ExitMaxDuration { get; set; }
        public float ExitMinArcHeight { get; set; }
        public float ExitMaxArcHeight { get; set; }
        public float PassengerYaw { get; set; }
        public float PassengerPitch { get; set; }
        public float PassengerRoll { get; set; }
        public float VehicleEnterAnimDelay { get; set; }
        public float VehicleExitAnimDelay { get; set; }
        public float CameraEnteringDelay { get; set; }
        public float CameraEnteringDuration { get; set; }
        public float CameraExitingDelay { get; set; }
        public float CameraExitingDuration { get; set; }
        public float CameraOffsetX { get; set; }
        public float CameraOffsetY { get; set; }
        public float CameraOffsetZ { get; set; }
        public float CameraPosChaseRate { get; set; }
        public float CameraFacingChaseRate { get; set; }
        public float CameraEnteringZoom { get; set; }
        public float CameraSeatZoomMin { get; set; }
        public float CameraSeatZoomMax { get; set; }
        public long UISkinFileDataID { get; set; }
        public short EnterAnimStart { get; set; }
        public short EnterAnimLoop { get; set; }
        public short RideAnimStart { get; set; }
        public short RideAnimLoop { get; set; }
        public short RideUpperAnimStart { get; set; }
        public short RideUpperAnimLoop { get; set; }
        public short ExitAnimStart { get; set; }
        public short ExitAnimLoop { get; set; }
        public short ExitAnimEnd { get; set; }
        public short VehicleEnterAnim { get; set; }
        public short VehicleExitAnim { get; set; }
        public short VehicleRideAnimLoop { get; set; }
        public int EnterAnimKitID { get; set; }
        public int RideAnimKitID { get; set; }
        public int ExitAnimKitID { get; set; }
        public int VehicleEnterAnimKitID { get; set; }
        public int VehicleRideAnimKitID { get; set; }
        public int VehicleExitAnimKitID { get; set; }
        public int CameraModeID { get; set; }
        public sbyte AttachmentID { get; set; }
        public sbyte PassengerAttachmentID { get; set; }
        public sbyte VehicleEnterAnimBone { get; set; }
        public sbyte VehicleExitAnimBone { get; set; }
        public sbyte VehicleRideAnimLoopBone { get; set; }
        public byte VehicleAbilityDisplay { get; set; }
        public long EnterUISoundID { get; set; }
        public long ExitUISoundID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
