//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class version
    {
        public string core_version { get; set; }
        public string core_revision { get; set; }
        public string db_version { get; set; }
        public Nullable<int> cache_id { get; set; }
        public int hotfix_cache_id { get; set; }
    }
}
