//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class warden_checks
    {
        public int id { get; set; }
        public Nullable<byte> type { get; set; }
        public string data { get; set; }
        public string str { get; set; }
        public Nullable<long> address { get; set; }
        public Nullable<byte> length { get; set; }
        public string result { get; set; }
        public string comment { get; set; }
    }
}
