//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class world_map_overlay
    {
        public long ID { get; set; }
        public string TextureName { get; set; }
        public int TextureWidth { get; set; }
        public int TextureHeight { get; set; }
        public long MapAreaID { get; set; }
        public long AreaID1 { get; set; }
        public long AreaID2 { get; set; }
        public long AreaID3 { get; set; }
        public long AreaID4 { get; set; }
        public int OffsetX { get; set; }
        public int OffsetY { get; set; }
        public int HitRectTop { get; set; }
        public int HitRectLeft { get; set; }
        public int HitRectBottom { get; set; }
        public int HitRectRight { get; set; }
        public long PlayerConditionID { get; set; }
        public long Flags { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
