//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class world_map_area
    {
        public string AreaName { get; set; }
        public float LocLeft { get; set; }
        public float LocRight { get; set; }
        public float LocTop { get; set; }
        public float LocBottom { get; set; }
        public int MapID { get; set; }
        public int AreaID { get; set; }
        public short DisplayMapID { get; set; }
        public short DefaultDungeonFloor { get; set; }
        public int ParentWorldMapID { get; set; }
        public int Flags { get; set; }
        public byte LevelRangeMin { get; set; }
        public byte LevelRangeMax { get; set; }
        public byte BountySetID { get; set; }
        public byte BountyBoardLocation { get; set; }
        public long ID { get; set; }
        public long PlayerConditionID { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
