//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class world_map_transforms
    {
        public long ID { get; set; }
        public float RegionMinX { get; set; }
        public float RegionMinY { get; set; }
        public float RegionMinZ { get; set; }
        public float RegionMaxX { get; set; }
        public float RegionMaxY { get; set; }
        public float RegionMaxZ { get; set; }
        public float RegionOffsetX { get; set; }
        public float RegionOffsetY { get; set; }
        public float RegionScale { get; set; }
        public int MapID { get; set; }
        public int AreaID { get; set; }
        public int NewMapID { get; set; }
        public int NewDungeonMapID { get; set; }
        public int NewAreaID { get; set; }
        public byte Flags { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
